<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
/**
 * @var Magenest\SalesPerson\Block\Adminhtml\Order\WarningMessage $block
 */
?>
<?php if ($block->getUserRole() == 1): ?>
<div id="messages">
    <div class="messages">
        <div class="message message-notice">
            <div><span class="account-balance price"><?= $block->escapeHtml($block->getWarningMessage()) ?></span></div>
        </div>
    </div>
</div>
<?php endif; ?>
