<?php
/**
 * Copyright © 2020 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Reward points extension
 * NOTICE OF LICENSE
 *
 * @author Magenest
 * @time: 19/11/2020 10:27
 */

/** @var \Magenest\RewardPoints\Block\Adminhtml\Membership\ListCustomerAssigned $block */
?>
<div class="message message-notice notice"><?= /* @noEscape */ __('You have selected %1 customer(s) that will be added points value.', $block->countCustomerSelected()) ?></div><br />
