<?php
/**
 * Created by PhpStorm.
 * User: thang
 * Date: 24/08/2018
 * Time: 14:57
 */

namespace Magenest\RewardPoints\Block\Adminhtml\Order\Creditmemo;

/**
 * Class Totals
 * @package Magenest\RewardPoints\Block\Adminhtml\Order\Creditmemo
 */
class Totals extends \Magento\Sales\Block\Adminhtml\Order\Creditmemo\Totals
{
    /**
     * @var \Magento\Sales\Model\OrderFactory
     */
    protected $orderFactory;

    /**
     * Totals constructor.
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Sales\Helper\Admin $adminHelper
     * @param \Magento\Sales\Model\OrderFactory $orderFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Sales\Helper\Admin $adminHelper,
        \Magento\Sales\Model\OrderFactory $orderFactory,
        array $data = []
    )
    {
        $this->orderFactory = $orderFactory;
        parent::__construct($context, $registry, $adminHelper, $data);
    }

    /**
     * @return $this|\Magento\Sales\Block\Adminhtml\Order\Creditmemo\Totals
     */
    protected function _initTotals()
    {
        parent::_initTotals(); // TODO: Change the autogenerated stub
        $label      = 'Reward Amount';
        $orderId    = $this->getSource()->getOrderId();
        $orderModel = $this->orderFactory->create()->load($orderId);
        if ($this->getSource()->getRewardPoint() || $orderModel->getRewardPoint()) {
            $rewardPoint = $this->getSource()->getRewardPoint() ? $this->getSource()->getRewardPoint() : $orderModel->getRewardPoint();
            $label       = 'Reward Amount (' . (int)$rewardPoint . ' points)';
        } else if ($this->getSource()->getRewardTier() || $orderModel->getRewardTier()) {
            $rewardTier = $this->getSource()->getRewardTier() ? $this->getSource()->getRewardTier() : $orderModel->getRewardTier();
            $label      = 'Reward Amount (' . (int)$rewardTier . ' %)';
        };
        if ($this->getSource()->getRewardAmount() > 0) {
            $total = new \Magento\Framework\DataObject([
                'code'  => $this->getNameInLayout(),
                'label' => __($label),
                'value' => -$this->getSource()->getRewardAmount(),
            ]);
            $this->addTotal($total, 'subtotal');
        }

        return $this;
    }
}
