<?php
/** @var \Magenest\Customer\Block\AccountInfo $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
$membershipData = $block->getMembershipData()
?>

<div class="customer-inner">
    <img class="customer-avt" src="<?= $escaper->escapeUrl($block->getCustomerAvatarUrl()) ?>" alt="default">
    <div class="customer-info">
        <span class="customer-name"><?= $block->getCustomerFullName() ?></span>
        <div class="customer-info-bottom">
            <?php if (!empty($membershipData->getId())) : ?>
                <a href="<?= $block->getUrlCustomerEdit() ?>" class="customer-rank"
                   style="background-color: <?= $block->escapeHtmlAttr($membershipData->getColorCode()) ?>;">
                    <?= $block->escapeHtml(__($membershipData->getName())) ?>
                </a>
            <?php endif; ?>

            <a href="<?= $block->getBaseUrl() ?>customer/account/logout" class="logout mobile-device">
                <?= __('Log out') ?>
            </a>
        </div>
    </div>
</div>

<?php
$scriptString = <<<script

    require(['jquery'], function($){
        let blockSidebarTitle = $('.block-collapsible-nav-content .nav.items > .nav.item:not(.affiliate) > a');
        let blockSidebarContent = $('.block-collapsible-nav-content .nav.child');

        blockSidebarTitle.on('click', function () {
            $(this).siblings('.nav.child').slideToggle();
        })

        $('.nav.item.current').children('.nav.child').slideToggle();

        if (window.location.pathname.includes('/affiliate')) {
            affiliateAccount();
        }

        function affiliateAccount() {
            $('.nav.items > .nav.item:not(.affiliate, .logout)').slideUp(300);
            $('.nav.items > .nav.item.affiliate > .nav.child').slideDown(300);
            $('.return-previous').slideDown(300);
        }
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

