<?php
/** @var \Magenest\Customer\Block\AccountInfo $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php ?>
<div class="customer-inner">
    <img class="customer-avt" src="<?= $escaper->escapeUrl($block->getCustomerAvatarUrl()) ?>" alt="default">
    <div class="customer-info">
        <span class="customer-name"><?= $block->getCustomerFullName() ?></span>
        <a href="<?= $block->getUrlCustomerEdit() ?>" class="customer-edit"><?= __('Edit profile') ?></a>
    </div>
</div>

<?php
$scriptString = <<<script

    require(['jquery'], function($){
        let blockSidebarTitle = $('.block-collapsible-nav-content .nav.items > .nav.item:not(.affiliate) > a');
        let blockSidebarContent = $('.block-collapsible-nav-content .nav.child');

        blockSidebarTitle.on('click', function () {
            $(this).siblings('.nav.child').slideToggle();
        })

        $('.nav.item.current').children('.nav.child').slideToggle();

        if (window.location.pathname.includes('/affiliate')) {
            affiliateAccount();
        }

        function affiliateAccount() {
            $('.nav.items > .nav.item:not(.affiliate)').slideUp(300);
            $('.nav.items > .nav.item.affiliate > .nav.child').slideDown(300);
            $('.return-previous').slideDown(300);
        }
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

