<?php
/** @var  $block \Magenest\NotificationBox\Block\Notification\Notification */
/** show icon notification when customer is login */
?>
<div class="notificationBox" data-bind="scope: 'notificationBox'">
    <div class="magenest-notification">
        <span class="magenest-notification-icon"></span>
        <span class="magenest-notification-text"><?= __('Notify') ?></span>
        <span class="notification-dots" style="display: none"></span>
        <div >
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "notificationBox": {
                        "component": "Magenest_NotificationBox/js/notification/notification",
                        "template" : "Magenest_NotificationBox/notification",
                        "config": {
                                    "url"                           : "<?=$block->getUrl("notibox/customer/notification")?>",
                                    "currentUrl"                    : "<?=$block->getUrl()?>",
                                    "backgroundColorValue"          : "<?=$block->getThemeColor()?>",
                                    "boxPositionClass"              : "<?=$block->getBoxPosition()?>",
                                    "notificationBoxWidth"          : "<?=$block->getBoxWidth()?>"
                        }
                    }
                }
            }
        }
    }
</script>

