<?php
/** @var  $block \Magenest\NotificationBox\Block\Customer\Tab\Notification */

$block->redirectIfNotLoggedIn();
$unread = $block->getUnreadNotification();
$allCustomerNotification = $block->getNotificationByCondition(null);
$allNotificationType = $block->getAllNotificationType();
?>

    <form action="">
        <div class="table-wrapper mgn-notification-wrapper">
            <div class="notification-page-head">
                <div class="mark-as-read-notification">
                    <a href="/" id="mark-all-as-read" ><?=__('Mark as read')?></a>
                </div>
            </div>

            <!--<div class="notification-controller">
                <div class="select_notification">
                    <select id="select_notification">
                        <option value="select-none"><?/*=__('None')*/?></option>
                        <option value="select-all" id="selectAll"><?/*=__('All')*/?></option>
                        <option value="select-read"><?/*=__('Read')*/?></option>
                        <option value="select-unread"><?/*=__('Unread')*/?></option>
                        <option value="select-important"><?/*=__('Important')*/?></option>
                        <option value="select-unimportant"><?/*=__('Unimportant')*/?></option>
                    </select>
                </div>

                <div class="reload-notification">
                    <a href=""><span class="mgn-noti-icon icon-refresh"></span></a>
                </div>
                <div class="delete-notification"><span class="mgn-noti-icon icon-remove"></span></div>

                <div class="mark-as-read-notification">
                    <a href="/" onclick="return false;"><?/*=__('Mark as read')*/?></a>
                </div>
            </div>
            <div class="listCategory">
                <?php /*foreach ($allNotificationType as $key=>$value){*/?>
                    <label>
                        <input type="button" value="<?/*= $value */?>" class="category-notification-btn <?/*=($block->getFilteredNotificationTypes() == $key)?'is_filter':''*/?>" id='filter-<?/*=$key*/?>'>
                        <span class="category-notification-label"><?/*= $value */?></span>
                    </label>
                <?php /*}*/?>
            </div>
            <div class="notification-selected">
                <p>All <span id="notification-selected">0</span> <?/*=__('notification on this page are selected. ')*/?><span id="select-all-notification" hidden><a href="/" onclick="return false;"><?/*= __('select all '.count($allCustomerNotification) .' notification on this page') */?> </a></span></p>
            </div>-->

            <div class="data table mgn-notification-table" id="my-notification-table">
                <?php if ($allCustomerNotification && count($allCustomerNotification)): ?>
                <?php foreach ($allCustomerNotification as $notification):?>
                    <div class="notification-item" id="<?= $notification['entity_id'] ?>">
                        <div class="notification-item-parent" style="background-color: <?= $notification['status'] ? '#fff' : '#F5FBF5' ?>">
                            <div class="notification-item-detail">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="<?= $notification['icon'] ?>" alt="<?= $notification['notification_type'] ?>">
                                    </span>
                                </span>
                                <div class="notification-item-info">
                                    <p class="notification-item-title">
                                        <?php echo __($notification['notification_type']) ?>
                                    </p>
                                    <p class="notification-item-description desktop-device">
                                        <?=$notification['full_description'] ?>
                                    </p>
                                    <span class="notification-item-created-at">
                                        <?php echo date('Y-m-d', strtotime($notification['created_at'])); ?>
                                    </span>
                                </div>
                            </div>
                            <p class="notification-item-description mobile-device">
                                <?=$notification['full_description'] ?>
                            </p>
                            <?php if ($notification['redirect_url']):?>
                                <a href="<?= $notification['redirect_url'] ?>" class="action view-order-detail desktop-device">
                                    <?= __('See details') ?>
                                </a>
                            <a href="<?= $notification['redirect_url'] ?>" class="action view-order-detail mobile-device">
                                <?= __('View Promotion Details') ?>
                            </a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php else: ?>
                    <div class="message info empty"><span><?php echo __('No any notification.'); ?></span></div>
                <?php endif ?>
                </tbody>
            </div>
        </div>
    </form>
    <?php if ($block->getChildHtml('pager')) : ?>
    <div class="notification-toolbar toolbar bottom"><?= $block->getChildBlock('pager')->setData('toolbar_number_title', 'Notify')->toHtml() ?></div>
    <?php endif ?>

<script type="text/x-magento-init">
        {
            "*": {
                "Magenest_NotificationBox/js/customer/tab/notification": {
                    "urlDelete":"<?= $block->getUrl('notibox/handleNotification/Delete')?>",
                    "urlMarkAsRead":"<?= $block->getUrl('notibox/handleNotification/MarkAllAsRead')?>",
                    "urlMarkImportant":"<?=$block->getUrl("notibox/handleNotification/MarkImportant")?>",
                    "urlViewNotification":"<?=$block->getUrl('notibox/handleNotification/viewNotification')?>",
                    "totalNotification": <?=count($allCustomerNotification)?>,
                    "baseUrl":"<?=$block->getUrl()?>"
                }
            }
        }
</script>
