<?php
/** @var  $block \Magenest\NotificationBox\Block\Customer\Tab\Notification */

$block->redirectIfNotLoggedIn();
$unread = $block->getUnreadNotification();
$allCustomerNotification = $block->getOrderNotification(null);
?>

<form action="">
    <div class="table-wrapper mgn-notification-wrapper">
        <div class="notification-page-head">
            <div class="mark-as-read-notification">
                <a href="/" id="mark-all-as-read" ><?=__('Mark as read')?></a>
            </div>
        </div>
        <div class="data table mgn-notification-table" id="my-notification-table">
            <div>
            <?php if ($allCustomerNotification && count($allCustomerNotification)): ?>
                <?php foreach ($allCustomerNotification as $orderNotifications):?>
                <?php $notification = array_shift($orderNotifications); ?>
                <div class="notification-item" id="<?= $notification['entity_id'] ?>">
                    <div class="notification-item-parent" style="background-color: <?= $notification['status'] ? '#fff' : '#F5FBF5' ?>">
                        <div class="notification-item-detail">
                        <span class="product-image-container">
                            <span class="product-image-wrapper">
                                <?= $block->getOrderFirstItemImageHtml($notification['additional_data']) ?>
                            </span>
                        </span>
                            <div class="notification-item-info">
                                <p class="notification-item-title">
                                    <?= $block->getOrderNotificationTitle($notification['additional_data']) ?>
                                </p>
                                <p class="notification-item-description desktop-device">
                                    <?=$notification['full_description'] ?>
                                </p>
                                <span class="notification-item-created-at parent <?= !$orderNotifications ? "hide-icon" : "" ?>">
                                <?php echo date('Y-m-d', strtotime($notification['created_at'])); ?>
                                </span>
                            </div>
                        </div>
                        <p class="notification-item-description mobile-device">
                            <?=$notification['full_description'] ?>
                        </p>
                        <a href="<?= $notification['redirect_url'] ?? $block->getOrderUrl($notification['additional_data']) ?>" class="action view-order-detail">
                            <?= __('View Order Details') ?>
                        </a>
                    </div>
                    <?php if ($orderNotifications):?>
                    <div class="notification-item-child" style="display: none">
                        <?php foreach ($orderNotifications as $notification): ?>
                            <?php
                                $title = $block->getOrderNotificationTitle($notification['additional_data']);

                            ?>
                        <div class="notification-item-detail">
                            <span class="line"></span>
                            <div class="notification-item-info">
                                <p class="notification-item-title">
                                    <?= $block->getOrderNotificationTitle($notification['additional_data']) ?>
                                </p>
                                <p class="notification-item-description">
                                    <?=$notification['full_description'] ?>
                                </p>
                                <span class="notification-item-created-at">
                                <?php echo date('Y-m-d', strtotime($notification['created_at'])); ?>
                                </span>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="message info empty"><span><?php echo __('No any notification.'); ?></span></div>
            <?php endif ?>
            </div>
        </div>
    </div>
</form>

<?php if ($block->getChildHtml('pager')) : ?>
    <div class="notification-toolbar toolbar bottom"><?= $block->getChildBlock('pager')->setData('toolbar_number_title', 'Notify')->toHtml() ?></div>
<?php endif ?>

<script type="text/x-magento-init">
        {
            "*": {
                "Magenest_NotificationBox/js/customer/tab/notification": {
                    "urlDelete":"<?= $block->getUrl('notibox/handleNotification/Delete')?>",
                    "urlMarkAsRead":"<?= $block->getUrl('notibox/handleNotification/MarkAllAsRead')?>",
                    "urlMarkImportant":"<?=$block->getUrl("notibox/handleNotification/MarkImportant")?>",
                    "urlViewNotification":"<?=$block->getUrl('notibox/handleNotification/viewNotification')?>",
                    "totalNotification": <?=count($allCustomerNotification)?>,
                    "baseUrl":"<?=$block->getUrl()?>"
                }
            }
        }
</script>

<script type="text/javascript">
    require(['jquery'], function($) {
        $('.notification-item-created-at.parent').on('click', function () {
            $(this).parents('.notification-item-parent').siblings('.notification-item-child').slideToggle(300);
            $(this).toggleClass('show');
        })
    });
</script>
