<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magenest\PhotoReview\Block\Review\Form $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$number_photo = $block->maxPhotoNumber();
$isRequired = $block->isRequiredPhoto();
$maxUploadSize = $block->getMaxUploadSize();
$isRequiredVideo = $block->isRequiredVideo();
$number_video = $block->maxVideoNumber();
$maxUploadVideoSize = $block->getMaxUploadVideoSize();
$currentProductId = $block->getProductInfo()->getId();
?>
<?php if ($block->getAllowWriteReviewFlag()): ?>
<div class="block review-add">
    <div class="write-review">
        <strong class="js-write-review" data-trigger="trigger-order-review"><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong>
    </div>
    <div class="block-content" id="popup-modal-review-product-sales-order">
        <?php $countRatings = 1; ?>
        <form action="<?= $block->escapeUrl($block->getAction()) ?>" enctype="multipart/form-data" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form', mageInit: {'validation':{}}">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset review-fieldset order-review-item" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <br/>
                <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <div class="review-field-rating">
                            <?php foreach ($block->getRatings() as $_rating): ?>
                                <div class="control review-control-vote">
                                    <?php $options = $_rating->getOptions();?>
                                    <?php $iterator = 1; foreach ($options as $_option): ?>
                                        <input
                                            type="radio"
                                            name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                            value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                            class="radio"
                                            data-validate="{'rating-required':true}"
                                            aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                        <label
                                            class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                            for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                            title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                            <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                        </label>
                                        <?php $iterator++; ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                    </fieldset>
                <?php endif ?>
                <div class="field review-field-summary review-field-suggest">
                    <?php foreach ($block->getLabelSummaryOptions() as $item): ?>
                        <label>
                            <input type="checkbox" name="<?= 'title[' . $item['value'] . ']'?>" id="<?= 'summary_field_' . $item['value'] ?>" autocomplete="off" value="<?= $item['value'] ?>">
                            <span><?= $item['label'] ?></span>
                        </label>
                    <?php endforeach; ?>
                </div>
                <div class="field review-field-nickname required">
                    <label>
                        <input type="text" placeholder="<?= $block->escapeHtml(__('Nickname')) ?>" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                    </label>
                </div>
                <div class="field review-field-text required review-field-box">
                    <div class="review-field-comment">
                        <textarea name="detail" id="review_field" placeholder="<?= $block->escapeHtml(__('Review of your product')) ?>" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                    </div>
                    <div class="note"><?= $block->escapeHtml(__('Up to 200 characters')) ?></div>
                </div>

                <div class="review-field-photo">
                    <?php
                    $i = 0;
                    while ($i < $number_photo){
                        $scope = "upload_photo_".$i;
                        ?>
                        <img id="photo-preview-<?= $i ?>" class="photo-preview" width="165" height="110" style="display: none"/>
                        <?php
                        $i++;
                    }
                    ?>
                </div>
                <div class="review-field-video">
                    <?php
                    $i = 0;
                    while ($i < $number_video){
                        $scope = "upload_video_".$i;
                        ?>
                        <video id="video-preview-<?= $i ?>" class="photo-preview" width="230" height="250" style="display: none" controls ></video>
                        <?php
                        $i++;
                    }
                    ?>
                </div>

                <div class="field photo-field-text review-field-photo-video" >
                    <span id="error-type-file-video" style="display:none; display: block; color: red"></span>
                    <?php
                    $i = 0;
                    while ($i < $number_photo){
                        $scope = "upload_photo_".$i;
                        ?>
                        <label class="upload-btn upload-photo" id="label-<?= $i ?>" style="<?= $i != 0 ? "display:none" : "" ?>">
                            <input data-next="<?= $i + 1 ?>" class="upload-photo" <?= $isRequired && $i == 0 ? "data-validate='{required:true}'" : "" ?> id="<?= $scope ?>" name="photo[<?= $i ?>]" type="file"/>
                            <span><?= $block->escapeHtml(__('More photos')) ?></span>
                        </label>
                        <?php
                        $i++;
                    }
                    ?>

                    <?php
                    $i = 0;
                    while ($i < $number_video){
                        $scope = "upload_video_".$i;
                        ?>
                        <label class="upload-btn upload-videos" id="label-<?= $i ?>" style="<?= $i != 0 ? "display:none" : "" ?>">
                            <input data-next="<?= $i + 1 ?>" class="upload-video" <?= $isRequiredVideo && $i == 0 ? "data-validate='{required:true}'" : "" ?> id="<?= $scope ?>" name="video[<?= $i ?>]" type="file" accept=".mp4"/>
                            <span><?= $block->escapeHtml(__('More videos')) ?></span>
                        </label>
                        <?php
                        $i++;
                    }
                    ?>
                </div>


            </fieldset>
            <?= $block->getChildHtml('form_fields_before') ?>
            <div class="modal-footer">
                <button type="button" id="cancel-rating-products" class="action action-back"><span><?= $block->escapeHtml(__('Cancel')) ?></span></button>
                <button type="submit" class="action action-complete submit-product-review-form"><span><?= $block->escapeHtml(__('Complete')) ?></span></button>
            </div>
        </form>
        <script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {}
    },
    "*": {
        "Magenest_PhotoReview/js/preview-photo": {
            "maxUploadSize" : <?= $block->escapeHtml($maxUploadSize); ?>
        },
        "Magenest_PhotoReview/js/preview-video": {
            "maxUploadSize" : <?= $block->escapeHtml($maxUploadVideoSize); ?>
        }
    }
}
</script>
        <?php endif ?>
    </div>
</div>


<?php $scriptString = <<<script
    require(['jquery'], function ($) {
        $(document).on('click', '.js-write-review',function(){
            $(this).hide();
            $(this).parent().parent().find('.block-content').slideDown();
            return false;
        });
        $(document).on('click', '#cancel-rating-products',function(){
            window.location.reload();
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<script>
    require(['jquery','Magento_Ui/js/modal/modal','mage/validation'], function($,modal){
        $(document).ready( function() {
            var countRatingsTotal = <?= $countRatings; ?>;
            var options = {
                'type': 'popup',
                'title': '<?= $block->escapeHtml(__('Product reviews')) ?>',
                'trigger': '[data-trigger=trigger-order-review]',
                'responsive': true,
                'modalClass':'popup-order-review',
                'buttons': []
            };

            modal(options, $('#popup-modal-review-product-sales-order'));
            $('#action-review').click(function (){
                $('#popup-modal-review-product-sales-order').modal('openModal');
            });
            for (let countRatings = 1; countRatings <= countRatingsTotal; countRatings++) {
                $('#photo_' + countRatings).change(function () {
                    var photoReviewId = '#photo_preview_' + countRatings;
                    var input = this;
                    var url = $(this).val();
                    var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                    if (input.files && input.files[0] && (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $(photoReviewId).css('display', 'block');
                            $(photoReviewId).attr('src', e.target.result);
                        }
                        reader.readAsDataURL(input.files[0]);
                    }
                });
                $('#video_' + countRatings).change(function () {
                    var videoReviewId = '#video_preview_' + countRatings;
                    var input = this;
                    var url = $(this).val();
                    var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                    if (input.files && input.files[0] && (ext == "mp4")) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $(videoReviewId).css('display', 'block');
                            $(videoReviewId).attr('src', e.target.result);
                        }
                        reader.readAsDataURL(input.files[0]);
                    }
                });
            }
        });
    });
</script>
