<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magenest\CustomCatalog\Helper\Helper;
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');

/** @var Helper $helperCatalog */
$helperCatalog =  $this->helper(Helper::class);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode         = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription  = false;
        $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode         = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription  = true;
        $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /** @var  $qtyBlock Magenest\QuantitySold\Block\Product\SoldQuantity */
    $qtyBlock = $block->getLayout()->createBlock('Magenest\QuantitySold\Block\Product\SoldQuantity');
    /** @var  $isSalableInAreaCode Magenest\CustomSource\Block\Product\IsSalableInAreaCode */
    $isSalableInAreaCode = $block->getLayout()->createBlock(
        'Magenest\CustomSource\Block\Product\IsSalableInAreaCode',
        'is_salable_in_area_code',
        [
            'data' => [
                'product_collection' => $_productCollection
            ]
        ]
    );

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */
    $viewMode ?> products-<?= /* @noEscape */
    $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */
                         $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */
                         $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <?php // Product Image ?>
                        <?= $block->getLayout()->createBlock(\Magenest\CustomCatalog\Block\Product\LabelDiscount::class)
                            ->setData('product', $_product)->toHtml(); ?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                            <?php if ($helperCatalog->isSalableInArea($_product)): ?>
                                <p class="label-out-of-stock"><?= __("Out of Stock") ?></p>
                            <?php endif; ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link" data-product-sku="<?= $block->escapeHtml($_product->getSku())?>"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>

                            <?= /* @noEscape */
                            $block->getProductPrice($_product) ?>

                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= strpos($pos, $viewMode . '-secondary') ?
                                        /* @noEscape */
                                        $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>

                                    <div class="stock available">
                                        <span>
                                            <?php if (!$helperCatalog->isSalableInArea($_product)): ?>
                                                <?= __('In Stock'); ?>
                                            <?php else: ?>
                                                <?= __('Out Of Stock'); ?>
                                            <?php endif; ?>
                                    </div>
                                    <div class="product-bottom">
                                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <div class="product-sell">
                                            <span><?= __('Sold') ?> </span>
                                            <span><?= $qtyBlock::numberPrefixEncode(
                                                    $qtyBlock->getProductSoldQuantity($_product)
                                                ) ?></span>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */
                                        $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                           title="<?= /* @noEscape */
                                           $_productNameStripped ?>"
                                           class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?= strpos($pos, $viewMode . '-actions') ?
                        /* @noEscape */
                        $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                        ) : '' ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }

    </script>
<?php endif; ?>
