<?php
/**
 * @var \Magenest\SocialLogin\Block\Adminhtml\SocialAccount\Monitor\OtherConnections $block
 */

$socialLoginData = $block->getSocialLoginData();
$totalRow = count($socialLoginData);
$rowNum = 0;
?>

<section class="admin__page-section other-connections">
    <div class="admin__page-section-title">
        <span class="title"><?= isset($escaper) ? $escaper->escapeHtml(__('Other Connections')) : $block->escapeHtml(__('Other Connections')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary other-connections-table">
                <thead>
                    <tr class="headings">
                        <th></th>
                        <th><span><?= isset($escaper) ? $escaper->escapeHtml(__('Users')) : $block->escapeHtml(__('Users')) ?></span></th>
                        <th><span><?= isset($escaper) ? $escaper->escapeHtml(__('Purchased Items')) : $block->escapeHtml(__('Purchased Items')) ?></span></th>
                        <th><span><?= isset($escaper) ? $escaper->escapeHtml(__('Amount')) : $block->escapeHtml(__('Amount')) ?></span></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($socialLoginData as $key => $item): ?>
                    <?php if($rowNum++ >= 3): ?>
                        <tr class="other-connection-row-type-<?= isset($escaper) ? $escaper->escapeHtmlAttr($item['social_login_type'] ?? '') : $block->escapeHtmlAttr($item['social_login_type'] ?? '') ?>">
                            <td class="type">
                                <span class="social-icon"></span>
                                <?= isset($escaper) ? $escaper->escapeHtml(ucfirst($item['social_login_type']) ?? null) : $block->escapeHtml(ucfirst($item['social_login_type']) ?? null) ?>
                            </td>
                            <td class="count-users">
                                <?= isset($escaper) ? $escaper->escapeHtml($item['users'] ?? 0) : $block->escapeHtml($item['users'] ?? 0) ?>
                            </td>
                            <td class="purchased-items">
                                <?= isset($escaper) ? $escaper->escapeHtml((int) $item['purchased_items'] ?? 0) : $block->escapeHtml((int) $item['purchased_items'] ?? 0) ?>
                            </td>
                            <td class="amount">
                                <?= isset($escaper) ? $escaper->escapeHtml($block->getPriceFormat($item['amount']) ?? 0) : $block->escapeHtml($block->getPriceFormat($item['amount']) ?? 0) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
