<?php
/**
 * @var \Magenest\CouponCode\Block\Coupon $block
 */
$coupon = $block->getCoupon();
/**
 * @var \Magenest\CouponCode\ViewModel\Coupon $viewModel
 */
$viewModel = $block->getViewModel();
$today = $viewModel->getToday();
if ($coupon->getSize() != 0) {
    $count = count($coupon); ?>
    <div class="coupon-list">
        <?php foreach ($coupon as $value): ?>
            <div class="coupon-item">
                <div class="container_coupon">
                    <?php
                    if (!empty($value->getData('images'))) {
                        $images = $viewModel->handleImage($value->getData('images'));
                    } else {
                        $images = $block->getViewFileUrl('Magenest_CouponCode::image/default-coupon.png');
                    }?>
                    <img class="coupon-image" src="<?= $block->escapeHtml($images); ?>"
                         alt="coupon"/>
                    <div class="information_mycoupon">
                        <strong><?= $block->escapeHtml($value->getStoreLabel() ?: $value->getData('name')) ?></strong>
                        <?php
                        $description = $value->getData('description');
                        if (strlen($description) <= 120) { ?>
                            <div class="description-coupon">
                                <?= $block->escapeHtml($description) ?>
                            </div>
                        <?php } else {
                            $description = $viewModel->handleDescription($description) ?>
                            <div class="description-coupon">
                                <div><?= $block->escapeHtml($description['display']) ?>
                                    <span class="see-more-coupon"
                                          class="seeMore"
                                          data-bind="scope:'seeMore'">
                                            <span data-bind='click: seeMore.bind($parent,
                                                            "<?= $block->escapeHtml($description['fixed']); ?>")'>
                                                            <?= $block->escapeHtml(__('...See more')) ?>
                                            </span>
                                        </span>
                                </div>
                            </div>
                        <?php
                        }?>
                        <?php
                        $exp = $value->getData('to_date');
                        if ($exp == null) { ?>
                            <div class="exp-coupon"><?= $block->escapeHtml(__('Exp: ')) .
                                $block->escapeHtml(__('Unlimited')); ?>
                            </div>
                        <?php } else { ?>
                            <div class="exp-coupon"><?= $block->escapeHtml(__('Exp: ')) .
                                $block->escapeHtml($exp); ?>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="information-condition">
                        <a href="<?= $block->escapeUrl($block->getUrl('voucher/details', ['ruleId' => $value->getRuleId(), 'evcode' => $value->getCode()])) ?>" target="_blank">
                            <?= $block->escapeHtml(__('Condition')) ?>
                        </a>
                    </div>
                    <?php if (!($block->checkClaimedCoupon($value->getData('coupon_id')))) {?>
                        <?php if ($viewModel->getCustomerGroup() == 0) { ?>
                            <div id="not-login-button"
                                 data-bind="scope:'warning'">
                            <span data-bind="click: warning.bind($parent, '<?= $block->escapeHtml($value->getData('name')) ?>')">
                                <button class="button-coupon-claim"></button>
                            </span>
                            </div>
                        <?php } else { ?>
                            <div id="claim-coupon-button"
                                 data-bind="scope:'claim'">
                            <span data-bind="click: claimCoupon.bind($parent,
                                                    '<?= $value->getData('code')?>')">
                                <!-- ko template: getTemplate() --><!-- /ko -->
                                <button class="button-coupon-claim"
                                        id="claim<?= $value->getData('code')?>"></button>
                            </span>
                            </div>
                        <?php } ?>
                    <?php } else { ?>
                        <button class ="button-coupon-claimed"></button>
                    <?php } ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php
} ?>
<?php if ($block->getPagerHtml()): ?>
    <?= $block->getPagerHtml(); ?>
<?php endif ?>
<script type="text/x-magento-init">
    {
                "#seeMore": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "seeMore": {
                                "component": "Magenest_CouponCode/js/coupon/action"
                            }
                        }
                    }
                },
                "#not-login-button": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "warning": {
                                "component": "Magenest_CouponCode/js/coupon/action"
                            }
                        }
                    }
                },
                "#claim-coupon-button": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "claim": {
                                "component": "Magenest_CouponCode/js/coupon/action"
                            }
                        }
                    }
                }
    }
</script>



