<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block-maintenance">
    <img class="kangaroo-bg" alt="kangaroo-logo" src="images/maintenance-bg.png">
    <img class="kangaroo-logo" alt="kangaroo-logo" src="images/logo.svg">
    <img class="kangaroo-icon" alt="kangaroo-icon" src="images/maintenance-icon.svg">
    <p class="title">Kangaroo sẽ sớm trở lại</p>
    <p class="description">Website của Kangaroo đang trong quá trình bảo trì và sẽ quay trở lại sớm.</p>
</div>

