<div class="affiliate-navigation mobile-device">
    <a href="<?= $this->getBaseUrl() ?>affiliate/account/index/" class="affiliate-navigation-item navigation-kcoin-wallet">
        <span class="icon icon-navigation-Kcoin"></span>
        <span><?= __('Kcoin Wallet') ?></span>
    </a>
    <a href="<?= $this->getBaseUrl() ?>affiliate/account/collaborator/" class="affiliate-navigation-item navigation-ctv">
        <span class="icon icon-navigation-ctv"></span>
        <span><?= __('Sponsored CTV') ?></span>
    </a>
    <a href="<?= $this->getBaseUrl() ?>affiliate/account/refer/" class="affiliate-navigation-item navigation-create-link">
        <span class="icon icon-navigation-create-link"></span>
        <span><?= __('Create Referral Link') ?></span>
    </a>
    <a href="<?= $this->getBaseUrl() ?>customer/account/create/" class="affiliate-navigation-item navigation-rank">
        <span class="icon icon-navigation-rank"></span>
        <span><?= __('Membership class') ?></span>
    </a>
    <a href="<?= $this->getBaseUrl() ?>affiliate/account/setting/" class="affiliate-navigation-item navigation-payment">
        <span class="icon icon-navigation-payment"></span>
        <span><?= __('Set up payment') ?></span>
    </a>
</div>
