<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Form\Account
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<div class="admin__page-section-title <?= $block->escapeHtmlAttr($block->getHeaderCssClass()) ?>">
    <span class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    <div class="actions"></div>
</div>
<div id="customer_account_fields" class="admin__page-section-content">
    <div class="admin__field field field-order_source  required _required" style="margin-bottom: 15px">
        <label class="label admin__field-label" for="order_source"><span><?= __('Order Source') ?></span></label>
        <div class="admin__field-control control">
            <select id="order_source" name="order_source"
                    class="required-entry required-entry _required select admin__control-select"
                    aria-required="true">
                <?php foreach ($block->getOrderSourceOptions() as $option): ?>
                    <option value="<?= $option['value'] ?>"><?= $option['label'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?= $block->getForm()->getHtml() ?>
</div>
<?php $scriptString = <<<script
    require(["prototype", "Magento_Sales/order/create/form"], function(){
        order.accountFieldsBind($('customer_account_fields'));
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
