<?php
/**
 * @var $block \Magenest\SocialLogin\Block\PopupModal\LoginButton
 */
$helper = $this->helper('Magenest\SocialLogin\Helper\SocialLogin')
?>
<?php $scriptString = <<<script
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        $(document).ready(function () {

            var options = {
                type: 'popup',
                modalClass: 'popup-authentication',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: []
            };
            modal(options, $('#modal_content'));
script;

    if (!$block->isLoggedIn() && $helper->isButtonEnabledModal()) {
        $scriptString .= <<<script
             $('.header > .header-top-right > .header-customer-notlogin > #customer-signin').bind('click', function (e) {
                    e.preventDefault();
                    if(this.href.indexOf("customer/account/login") != -1){

                        $('#modal_content').modal('openModal');
                    }
                });
        script;
    }

$scriptString .= <<<script
        })
    })
script;
?>
<?= isset($secureRenderer) ? $secureRenderer->renderTag('script', [], $scriptString, false) : '<script>' . $scriptString . '</script>' ?>
