<?php

?>
<?php
/** @var Magenest\Affiliate\Block\Account\Withdraw $block */
?>
<div class="field payment-method required withdraw-payment-method-detail required" id="withdraw-payment-method-paypal">
    <label for="paypal_email" class="label"><span><?= __('Paypal Email Associate') ?></span></label>
    <div class="input-box">
        <input type="text" id="paypal_email" name="paypal_email" title="<?= __('Paypal Email Address') ?>"
               class="input-text required-entry validate-email"
               value="<?= $block->getFormData('paypal_email') ?>"/>
    </div>
</div>
