<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var History $block
 * @var \Magenest\NotifyOrderComment\Helper\Data $dataHlp
 *
 */
$dataHlp = $this->helper(\Magenest\NotifyOrderComment\Helper\Data::class);
$helperData = $this->helper(\Magenest\SalesPerson\Helper\AssignedToSales::class);

use Magento\Sales\Block\Adminhtml\Order\View\History;

?>
<div id="order_history_block" class="edit-order-comments">
    <?php if ($block->canAddComment()): ?>
        <div class="order-history-block" id="history_form">
            <div class="admin__field">
                <label for="history_status" class="admin__field-label"><?= /* @noEscape */
                    __('Status') ?></label>
                <div class="admin__field-control">
                    <select name="history[status]" id="history_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                            <option value="<?= $block->escapeHtml($_code) ?>"<?php if ($_code == $block->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($_label) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label for="history_title" class="admin__field-label">
                    <?= /* @noEscape */
                    __('Title') ?>
                </label>
                <div class="admin__field-control">
                    <input name="history[title]"
                              type="text"
                              id="history_title"
                              class="admin__control-textarea" />
                </div>
            </div>
            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?= /* @noEscape */
                    __('Comment') ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="order-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <?php if ($block->canSendCommentEmail()): ?>
                            <input name="history[is_customer_notified]"
                                   type="checkbox"
                                   id="history_notify"
                                   class="admin__control-checkbox"
                                   value="1"/>
                            <label class="admin__field-label" for="history_notify">
                                <?= /* @noEscape */ __('Notify Customer by Email') ?>
                            </label>
                        <?php endif; ?>
                    </div>
                    <div class="admin__field admin__field-option">
                        <input name="history[is_customer_notified_store_front]"
                               type="checkbox"
                               id="history_notify_store_front"
                               class="admin__control-checkbox"
                               value="1"/>
                        <label class="admin__field-label" for="history_notify_store_front">
                            <?= /* @noEscape */ __('Notify Customer on Store front (Notification)') ?>
                        </label>
                    </div>
                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1"/>
                        <label class="admin__field-label" for="history_visible">
                            <?= /* @noEscape */ __('Visible on Storefront') ?>
                        </label>
                    </div>
                    <div class="admin__field admin__field-option">
                        <input name="history[history_notify_to_admin]"
                               type="checkbox"
                               id="history_notify_to_admin"
                               class="admin__control-checkbox" value="1" />
                        <label class="admin__field-label" for="history_notify_to_admin">
                            <?= /* @noEscape */ __('Notify Admin by Email') ?>
                        </label>
                    </div>
                    <div id="div_email" class="admin__field _required">
                        <label class="admin__field-label" for="history_notify_to_admin">
                            <?= /* @noEscape */ __('Email') ?>
                        </label>
                        <div class="admin__field-control">
                            <input name="history[history_notify_email_admin]"
                                   type="text"
                                   id="history_notify_email_admin"
                                   class="input-text admin__control-text required"
                                   value="<?= $dataHlp->getEmailDefaultConfig() ?>"
                            />
                        </div>
                    </div>

                </div>
                <?php
                if(!$helperData->authorizationRole($this->getOrder())):
                ?>
                    <div class="order-history-comments-actions">
                        <?= $block->getChildHtml('submit_button') ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <ul class="note-list">
        <?php foreach ($block->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
            <li class="note-list-item">
                <span class="note-list-date"><?= /* @noEscape */
                    $block->formatDate($_item->getCreatedAt(), IntlDateFormatter::MEDIUM) ?></span>
                <span class="note-list-time"><?= /* @noEscape */
                    $block->formatTime($_item->getCreatedAt(), IntlDateFormatter::MEDIUM) ?></span>
                <span class="note-list-status"><?= $block->escapeHtml($dataHlp->getNameByUserId($_item->getUserId())) ?></span>
                <span class="note-list-status"><?= $block->escapeHtml($_item->getStatusLabel()) ?></span>
                <span class="note-list-customer">
                <?= /* @noEscape */
                __('Customer') ?>
                    <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                        <span class="note-list-customer-notapplicable"><?= /* @noEscape */
                            __('Notification Not Applicable') ?></span>
                    <?php elseif ($_item->getIsCustomerNotified()): ?>
                        <span class="note-list-customer-notified"><?= /* @noEscape */
                            __('Notified') ?></span>
                    <?php else: ?>
                        <span class="note-list-customer-not-notified"><?= /* @noEscape */
                            __('Not Notified') ?></span>
                    <?php endif; ?>
            </span>
                <?php if ($_item->getComment()): ?>
                    <div class="note-list-comment"><?= $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script>
        require(['prototype'], function () {

            if ($('order_status')) $('order_status').update('<?= $block->escapeJs($block->escapeHtml($block->getOrder()->getStatusLabel())) ?>');

        });
    </script>
</div>
<script>
    require([
        'jquery',
    ], function ($) {
        var check;
        $("#div_email").hide();
        $("#history_notify_to_admin").on("change", function(){
            check = $(this).is(":checked");
            if(check) {
                $("#div_email").show();
            } else {
                $("#div_email").hide();
            }
        });
    })
</script>
