
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>


<?php $scriptString = <<<script
	require(['jquery','slick'], function ($) {

		function slickInitialize(){
			jQuery('.home-block10 .post-list:not(".slick-slider")').slick({
		    	prevArrow: '<span class="slick-prev"><span></span></span>',
		        nextArrow: '<span class="slick-next"><span></span></span>',

		        infinite: false,
		        speed: 300,
		        autoplay: false,
		        autoplaySpeed: 2000,
		        centerMode: false,
		        centerPadding: '0px',
		        arrows: true,
		        dots: false,
		        slidesToShow: 4,
		        slidesToScroll: 4,
		        responsive: [

		            {
		              breakpoint: 992,
		              settings: {
		                slidesToShow: 2,
		                slidesToScroll: 1,
		                variableWidth: true
		              }
		            },
		            {
		              breakpoint: 768,
		              settings: {
		              	infinite: true,
		                slidesToShow: 1,
		                slidesToScroll: 1,
		                variableWidth: true
		              }
		            },
		            {
		              breakpoint: 640,
		              settings: {
		              	infinite: true,
		                slidesToShow: 1,
		                slidesToScroll: 1,
		                variableWidth: true
		              }
		            }
		        ]
	    	});
            if(jQuery(window).width()<767){

                jQuery('.home-block2 .pagebuilder-column-group:not(.slick-slider),.home-block4 .pagebuilder-column-group:not(.slick-slider)').slick({
                    infinite: false,
                    speed: 300,
                    centerMode: false,
                    centerPadding: '0px',
                    slidesToShow:3,
                    slidesToScroll: 3,
                    arrows: true,
                    dots: false,
                    prevArrow: '<span class="slick-prev"></span>',
                    nextArrow: '<span class="slick-next"></span>',
                });
               
            }else{
                $('.home-block2 .pagebuilder-column-group.slick-slider,.home-block4 .pagebuilder-column-group.slick-slider').slick('unslick');
            }

            if(jQuery(window).width()<1023){


                jQuery('.home-block6 .pagebuilder-column-group:not(.slick-slider)').slick({
                    infinite: false,
                    speed: 300,
                    centerMode: false,
                    centerPadding: '0px',
                    arrows: true,
                    dots: false,
                    prevArrow: '<span class="slick-prev"></span>',
                    nextArrow: '<span class="slick-next"></span>',
                    rows: 2,
                    slidesPerRow: 1,
                    slidesToShow:2,
                    slidesToScroll: 2,

                });
               
            }else{
                $('.home-block6 .pagebuilder-column-group.slick-slider').slick('unslick');
            }
        }

    	jQuery(document).ready(function(e){
            slickInitialize();
        });

        jQuery(window).resize(function(){
            slickInitialize();
        });



	});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>