<?php
/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $helper \Magenest\Cdp365\ViewModel\CatalogHelper */
$product = $block->getProduct();
$images = $product->getExtensionAttributes()->getMedia();
$helper = $block->getHelper();
$categoryList = $helper->getCategoryList($product);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magenest_Cdp365/js/analytics/product": {
                "brand": "KANGAROO",
                "id": "<?= $block->escapeJs($product->getSku()) ?>",
                "name": "<?= $block->escapeJs($product->getName()) ?>",
                "original_price": "<?= $block->escapeJs($product->getPriceInfo()->getPrice('regular_price')->getValue()) ?>",
                "price": "<?= $block->escapeJs($product->getFinalPrice()) ?>",
                "page_url": "<?= $block->escapeJs($product->getProductUrl()) ?>",
                "image_url": "<?= $block->escapeJs(!empty($images) ? reset($images)->getUrl() : "") ?>"	,
                "main_category":  "<?= $categoryList[0] ?? "" ?>",
                "category_level_1": "<?= $categoryList[1] ?? "" ?>",
                "category_level_2": "<?= $categoryList[2] ?? "" ?>"
            }
        }
    }
</script>
