<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Free Gift for Magento 2
*/
?>
<?php /** @var \Amasty\Promo\Block\Add $block */ ?>
<div class="ampromo-items-add" data-ampopup-js="message">
	<?= $block->escapeHtml(__('Cart is eligible to receive gifts')) ?>
	<a href="#" data-role="ampromo-popup-show"><?= $block->escapeHtml(__('Choose a gift now')) ?></a>
</div>
