<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();

// Regular Price not include product option price
$regularPrice = $product->getPrice() * $_item->getQty();
$specialPrice = $product->getFinalPrice() * $_item->getQty();

if ($optionIds = $product->getCustomOption('option_ids')) {
    $finalPriceOption = 0;
    // Get all value of option item card
    foreach (explode(',', $optionIds->getValue()) as $optionId) {
        if ($option = $product->getOptionById($optionId)) {
            $confItemOption = $product->getCustomOption('option_' . $option->getId());

            $group = $option->groupFactory($option->getType())
                ->setOption($option)
                ->setConfigurationItemOption($confItemOption);
            $finalPriceOption += $group->getOptionPrice($confItemOption->getValue(), $finalPriceOption) * $_item->getQty();
        }
    }
    if ($finalPriceOption) {
        // Calculate proportion actual of product not include price option and regular option
        $proportion = ($specialPrice - $finalPriceOption) / $regularPrice;
        $regularPrice += ($finalPriceOption / $proportion);
    }
}

$regularPriceFormat = $block->convertPrice($regularPrice, true);
$specialPriceFormat = $block->convertPrice($specialPrice, true);
$displayDiscount = false;
$discountPercent = "0%";

if ($regularPriceFormat !== $specialPriceFormat) {
    $displayDiscount = true;
    $discountPercent = -round((($regularPrice - $specialPrice) / $regularPrice) * 100, 2);
    $discountPercent = $discountPercent . "%";
}

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <div class="item-list">
            <?php if ($block->hasProductUrl()) : ?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else : ?>
                <span class="product-item-photo">
                <?php endif; ?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()) : ?>
            </a>
        <?php else : ?>
            </span>
        <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) : ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) : ?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt class="title-options"><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd class="content-options">
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <div class="item-price mobile-device">
                    <?= $specialPriceFormat ?>
                    <?php if ($displayDiscount): ?>
                        <div class="discount-list">
                            <div class="discount-item left"><?= $regularPriceFormat ?></div>
                            <div class="discount-item right"><?= $discountPercent ?></div>
                        </div>
                    <?php endif ?>
                </div>
                <div class="item-actions">
                    <div class="actions-toolbar">
                        <?= /* @noEscape */
                        $block->getActions($_item) ?>
                    </div>
                </div>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </div>
    </td>

    <?php if ($canApplyMsrp) : ?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span
                        class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else : ?>
        <td class="col price desktop-device" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <div class="item-price">
                <?= $specialPriceFormat ?>
                <?php if ($displayDiscount): ?>
                    <div class="discount-list">
                        <div class="discount-item left"><?= $regularPriceFormat ?></div>
                        <div class="discount-item right"><?= $discountPercent ?></div>
                    </div>
                <?php endif ?>
                </div>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty input-group">
                <span class="qty-number qty-minus"></span>
                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </label>
                <span class="qty-number qty-plus"></span>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) : ?>
            <span class="cart msrp subtotal">--</span>
        <?php else : ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
</tbody>
<script type="text/x-magento-init">
    {
       "*": {
            "Magento_Checkout/js/cart-quantitynumber": {}
       }
    }

</script>
