<?php
/**
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magenest\MapList\Block\Adminhtml\Location\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;

class AddSeo extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        array $data
    ) {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }
    public function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('maplist_location_edit');
        $data = $model->getData();
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('location_');

        $fieldset = $form->addFieldset(
            'seo_fieldset',
            array(
                'legend' => __('SEO'),
            )
        );
        if ($model->getId()) {
            $fieldset->addField(
                'location_id',
                'hidden',
                array('name' => 'location_id')
            );
        }

        $fieldset->addField(
            'meta_title',
            'text',
            array(
                'name' => 'meta_title',
                'label' => __('Meta Title'),
                'title' => __('meta_title'),
                'required' => false
            )
        );
        $fieldset->addField(
            'meta_description',
            'textarea',
            array(
                'name' => 'meta_description',
                'label' => __('Meta Description'),
                'title' => __('meta_description'),
                'required' => false
            )
        );
        $fieldset->addField(
            'meta_keywords',
            'textarea',
            array(
                'name' => 'meta_keywords',
                'label' => __('Meta Keywords'),
                'title' => __('meta_keywords'),
                'required' => false
            )
        );
        $form->setValues($data);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    public function getTabLabel()
    {
        return __('SEO');
    }

    public function getTabTitle()
    {
        return __('SEO');
    }

    public function canShowTab()
    {
        return true;
    }

    public function isHidden()
    {
        return false;
    }
}
