<?php
/**
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magenest\MapList\Block\Adminhtml\Location\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;
use Magenest\MapList\Model\Config\Source\Options;

class LocationAttribute extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
    protected $_options;

    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        Options $options,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        array $data
    )
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        $this->_options = $options;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    public function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('maplist_location_edit');
        $data = $model->getData();
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('location_');

        $fieldset = $form->addFieldset(
            'attribute_fieldset',
            array(
                'legend' => __('Location Attributes'),
            )
        );
        if ($model->getId()) {
            $fieldset->addField(
                'location_id',
                'hidden',
                array('name' => 'location_id')
            );
        }

        $fieldset->addField(
            'parking',
            'select',
            array(
                'name' => 'parking',
                'label' => __('Parking'),
                'title' => __('parking'),
                'options' => $this->_options->toOptionArray(),
                'required' => false
            )
        );
        $fieldset->addField(
            'atm',
            'select',
            array(
                'name' => 'atm',
                'label' => __('ATM'),
                'title' => __('atm'),
                'options' => $this->_options->toOptionArray(),
                'required' => false
            )
        );
        $fieldset->addField(
            'new_arrivals',
            'date',
            array(
                'name' => 'new_arrivals',
                'label' => __('New Arrivals'),
                'title' => __('new arrivals'),
                'date_format' => 'MM/dd/Y',
                'readonly' => true,
                'required' => false,
                'time' => false,
            )
        );
        $fieldset->addField(
            'payment_methods',
            'multiselect',
            array(
                'name' => 'payment_methods',
                'label' => __('Payment Methods'),
                'title' => __('payment methods'),
                'values' => $this->_options->getAllPaymentMethods(),
                'required' => false,
            )
        );
        if (!isset($data['parking'])) {
            $data['parking'] = 1;
        }
        if (!isset($data['atm'])) {
            $data['atm'] = 1;
        }
        $form->setValues($data);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    public function getTabLabel()
    {
        return __('Location Attributes');
    }

    public function getTabTitle()
    {
        return __('Location Attributes');
    }

    public function canShowTab()
    {
        return true;
    }

    public function isHidden()
    {
        return false;
    }
}
