<?php
/** @var \Magento\Sales\Block\Order\History $block */
/** @var \Magenest\OrderCancel\ViewModel\FrontendCancel $orderCancel */
$_orders = $block->getOrders();
$orderCancel = $block->getOrderCancel();
?>
<?= $block->getChildHtml('info') ?>
<ul class="orders-history-tab">
    <li class="orders-tab-item <?= $block->getData('state') ? '' : 'active' ?>">
        <a class="" <?= $block->getData('state') ? "href=\"" . $block->getUrl('sales/order/history') . "\"" : "" ?> ><?= __('All') ?></a>
    </li>
    <?php foreach ($block->getStatuses() as $key => $data): ?>
    <?php $count = $block->getTotalCountByState($key)?>
    <li class="orders-tab-item <?= $block->getData('state') == $key ? 'active' : '' ?>">
        <a <?= $block->getData('state') !=$key ? "href=\"" . $block->getUrl($data['url']) . "\"" : "" ?> ><?= __($data['label']) ?><span><?= $count ? "({$count})" : "" ?></span></a>
    </li>
    <?php endforeach; ?>
</ul>
<div class="block table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Delivery address')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col total mobile-device"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <?php $_shippingAddress = $_order->getShippingAddress(); ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order')) ?>" class="col id">#<?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Street Address')) ?>" class="col shipping">
                        <?= $_shippingAddress ? implode(", ", array_merge($_shippingAddress->getStreet(), [
                            $_shippingAddress->getWard(),
                            $_shippingAddress->getDistrict(),
                            $_shippingAddress->getCity()
                        ])) : '' ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status <?= $block->escapeHtml($_order->getStatus()) ?>"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total mobile-device"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if (!count($_orders)): ?>
        <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
    <?php endif ?>
</div>
<?php if ($this->getChildHtml('pager')) : ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getChildBlock('pager')->setData('toolbar_number_title', 'Order')->toHtml() ?></div>
<?php endif ?>
<script>
    require(['jquery'], function ($) {
        $('.orders-tab-item:not(active)').click(function () {
            window.location.href = $(this).find('a').attr('href');
        });
    })
</script>
