<?php
/**
 * @var $block FishPig\WordPress\Block\Post
 */
?>

<?php $recommderList = $block->getRecommendPost(3) ?>
<div class="related-post">
    <h2><?= __('Recommend Post') ?></h2>
    <ul>
        <?php foreach ($recommderList as $item): ?>
            <li>
                <a href="<?= $block->escapeUrl($item->getUrl()) ?>" class="title" title="<?= $block->escapeHtml($item->getPostTitle()) ?>">
                    <div class="item-post">
                    <?php if ($image = $item->getImage()): ?>
                        <?php $imageUrl = $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(600, null) : '' ?>
                        <img src="<?= $block->escapeUrl($imageUrl) ?>" alt="<?= $block->escapeHtml($item->getName()) ?>" jsname="HiaYvf" jsaction="load:XAeZkd;"
                             class="n3VNCb" data-noaft="1">
                    <?php else: ?>
                        <img src="<?= $block->escapeUrl($block->getDefaultImage()) ?>" alt="<?= $block->escapeHtml($item->getName()) ?>" jsname="HiaYvf" jsaction="load:XAeZkd;"
                             class="n3VNCb" data-noaft="1">
                    <?php endif; ?>
                    </div>
                </a>
                <div class="title">
                    <a href="<?= $block->escapeUrl($item->getUrl()) ?>" class="title" title="<?= $block->escapeHtml($item->getPostTitle()) ?>">
                        <?= $item->getPostTitle() ?>
                    </a>
                </div>
                <div class="content">
                    <p><?= $item->getExcerpt(60) ?></p>
                </div>
                <div class="date-post"><?= $block->formatDateVietNam($item->getPostDate("d/m/Y")) ?></div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
