<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 * @var \FishPig\WordPress\Model\Post $block
 */
?>
<?php if ($post = $block->getPost()): ?>
    <div class="post-list-item">

        <?php if (!$post->isViewableForVisitor()): ?>
            <?= $block->getPasswordProtectHtml() ?>
        <?php else: ?>
            <div class="post-entry">
                <div class="post-image">
                    <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getName()) ?>">
                    <?php if ($image = $post->getImage()): ?>
                        <?php $imageUrl = $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(600, null) : '' ?>
                        <img src="<?= $block->escapeUrl($imageUrl) ?>" alt="<?= $block->escapeHtml($post->getName()) ?>"/>
                    <?php else: ?>
                        <img src="<?= $block->escapeUrl($block->getDefaultImage()) ?>" alt="<?= $block->escapeHtml($post->getName()) ?>"/>
                    <?php endif; ?>
                    </a>
                </div>
                <div class="post-title">
                    <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getName()) ?>">
                        <?= $block->escapeHtml($post->getName()) ?>
                    </a>
                </div>
                <div class="post-excerpt">
                    <p><?= $post->getExcerpt(60) ?></p>
                </div>
                <div class="post-meta">
                    <div class="post-date post-meta-item">
                        <?= $post->getPostDate("d/m/Y") ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
