<?php

namespace Magenest\Customer\Ui\Component\Listing;

class CustomerDataProvider extends \Magento\Customer\Model\ResourceModel\Grid\Collection
{
    public function addFieldToFilter($field, $condition = null)
    {
        if ($field === 'street') {
            $field = 'cae.street';
        }

        if ($field === 'city_id') {
            $field = 'cae.city_id';
        }

        return parent::addFieldToFilter($field, $condition); // TODO: Change the autogenerated stub
    }
    protected function _initSelect()
    {
        parent::_initSelect();

        $this->addFilterToMap('entity_id', 'main_table.entity_id');

        $this->getSelect()->joinLeft(
            ['ce' => $this->getTable('customer_entity')],
            'main_table.entity_id = ce.entity_id'
        )->joinLeft(
            ['cae' => $this->getTable('customer_address_entity')],
            'ce.default_shipping = cae.entity_id',
            ['city','street']
        );
        return $this;
    }
}
