<?php
/**
 * @var $block \Magenest\CustomSource\Block\Element\AreaPopup
 */
$helper = $this->helper('Magenest\MapList\Helper\Config');
$data = $block->getCookie('area_code');
$area = $block->getAreaByName($data);

?>
<?php if ($block->getAreaPopupEnable()): ?>
    <div class="header-store" id="area-select-option">
        <div class="header-store-action">
            <?php if ($block->getCurrentAreaCode()): ?>
                <span id="area-prefix"><?php echo $block->escapeHtml(__('Area')) ?></span>
                <span id="area-label"><?php echo ": " . $block->getCurrentAreaCodeLabel() ?></span>
            <?php else: ?>
                <span id="area-prefix"><?php echo $block->escapeHtml(__('Choose Area')) ?></span>
                <span id="area-label"></span>
            <?php endif; ?>
        </div>

        <div class="header-store-menu">
            <div class="header-store-menu-content">
                <?php echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('location.popup.image')
                    ->toHtml();
                ?>
                <div id="area-popup-modal">
                    <p class="title"><?php echo __('Welcome to') ?></p>
                    <img class="kangaroo-logo" src="<?php echo $block->getViewFileUrl('images/kangaroo-logo.svg'); ?>"
                         alt="kangaroo-logo">
                    <p class="description"><?php echo __('Please select your desired delivery area so that we can better serve you') ?></p>
                    <form action="#" class="popup-form-data-submit">
                        <div class="location-list">
                            <?php foreach ($block->getAreaData() as $item): ?>
                                <div class="location-item">
                                    <input type="radio" id="<?php echo $item['value'] ?>" name="area"
                                           value="<?php echo $item['value'] ?>">
                                    <label for="<?php echo $item['value'] ?>">
                                        <span class="custom-check radio"></span>
                                        <?php echo $item['label'] ?>
                                    </label>
                                </div>
                            <?php endforeach ?>
                        </div>
                        <button class="action primary" type="submit"><?php echo __('Confirm') ?></button>
                        <div class="note" style="display: none">
                            <strong><?php echo __('Warning!') ?></strong> <?php echo __('When you change the area, the item in the cart will be deleted') ?>
                        </div>
                    </form>
                    <img class="kangaroo-image-bottom"
                         src="<?php echo $block->getViewFileUrl('images/location-popup-bottom-image.png'); ?>"
                         alt="kangaroo-image">
                </div>
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Theme/js/area-popup": {}
            }

        }
    </script>

<?php endif ?>
<script>
    require([
        'jquery',
        'mage/url',
        'jquery/jquery.cookie'
    ], function ($,urlBuilder) {

        var currentLocation = [];
        if (navigator.geolocation) {
            if (typeof navigator.permissions != "undefined" && typeof navigator.permissions.query != "undefined") {
                navigator.permissions.query({
                    name: 'geolocation'
                }).then(function (result) {
                    if (result.state == 'prompt' || result.state == 'granted') {
                        getLocation();
                    }
                });
            } else {
                if ($.cookie('is-location-denied')) {
                    return;
                }
                if ($.cookie('current-location')) {
                    $('.header-location > span').html($.cookie('current-location'));
                    return;
                }
                getLocation();
            }
        }
        if ($.cookie('current-location')) {
            $('.header-location > span').html($.cookie('current-location'));
        }
        function assignAreaCode(province) {
            let url = urlBuilder.build("customsource/quote/assignareacode");
            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'json',
                data: {
                    province: province,
                },
                showLoader: true,
                success: function(response) {
                    console.log(response);
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        }
        function getLocation() {
            navigator.geolocation.getCurrentPosition(function (position) {
                if (!$.cookie('current-location') ||
                    Math.sqrt(Math.abs(position.coords.latitude - $.cookie('current-lat')) ** 2 +
                        Math.abs(position.coords.longitude - $.cookie('current-long')) ** 2) >= 0.005) {
                    $.get("https://rsapi.goong.io/Geocode?latlng=" + position.coords.latitude + "," +
                        position.coords.longitude + "&api_key=<?php echo $helper->getApiKey() ?>", function (data) {
                        if (data.results) {
                            let glocation = data.results[0];
                            let province = glocation.compound.province;
                            assignAreaCode (province);

                            $.cookie('current-location', currentLocation.join(", "), {expires: 365});
                            $.cookie('current-lat', position.coords.latitude, {expires: 365});
                            $.cookie('current-long', position.coords.longitude, {expires: 365});
                            $.cookie('is_allowed',1);
                            if ($.cookie('current-location')) {
                                $('.header-location > span').html($.cookie('current-location'));
                            }
                        }
                    })
                }
            }, function (error) {
                $.cookie('is-location-denied', true, {expires: 365});
            })
        }
    });

</script>
