<?php

namespace Magenest\RewardPoints\Controller\Voucher;

use Magenest\CouponCode\Model\ClaimCouponFactory;
use Magenest\CouponCode\Model\ResourceModel\ClaimCoupon;
use Magento\Customer\Model\Session;
use Magento\Framework\App\Action\Context;
use Magento\Framework\Data\Form\FormKey\Validator;
use Magento\SalesRule\Model\CouponFactory;
use Magento\SalesRule\Model\ResourceModel\Coupon as CouponResourceModel;
use Psr\Log\LoggerInterface;

class Claim extends \Magenest\CouponCode\Controller\Coupon\Claim
{
    public function __construct(
        Context             $context,
        Validator           $formKeyValidator,
        ClaimCoupon         $resource,
        ClaimCouponFactory  $couponFactory,
        LoggerInterface     $logger,
        CouponFactory       $couponMagentoFactory,
        CouponResourceModel $couponResourceModel,
        Session             $customerSession
    )
    {
        parent::__construct(
            $context,
            $formKeyValidator,
            $resource,
            $couponFactory,
            $logger,
            $couponMagentoFactory,
            $couponResourceModel,
            $customerSession
        );
    }
    public function execute()
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }
}
