<h2 class="kangaroo-shopping-title mobile-device"><?= __('Sale with KangarooShopping') ?></h2>
<div class="block-general-statistical">
    <div class="statistical-item this-month">
        <p class="statistical-title"><?= __('This month') ?></p>
        <div class="block-flex">
            <div class="block-sales">
                <label class="label"><?= __('Sales') ?></label>
                <p class="value price">30.000.000đ</p>
                <div class="block-commission">
                    <p class="value price">
                        500.000đ
                    </p>
                    <label class="label"><?= __('Temporary commission') ?></label>
                </div>
            </div>
            <div class="block-pending">
                <label class="label"><?= __('Pending') ?></label>
                <p class="value price">30.000.000đ</p>
                <div class="block-commission">
                    <p class="value price">
                        500.000đ
                    </p>
                    <label class="label"><?= __('Temporary commission') ?></label>
                </div>
            </div>
        </div>
    </div>
    <div class="statistical-item today">
        <p class="statistical-title"><?= __('Today') ?></p>
        <div class="block-flex">
            <div class="block-sales">
                <label class="label"><?= __('Sales') ?></label>
                <p class="value price">30.000.000đ</p>
                <div class="block-commission">
                    <p class="value price">
                        500.000đ
                    </p>
                    <label class="label"><?= __('Temporary commission') ?></label>
                </div>
            </div>
            <div class="block-pending">
                <label class="label"><?= __('Pending') ?></label>
                <p class="value price">30.000.000đ</p>
                <div class="block-commission">
                    <p class="value price">
                        500.000đ
                    </p>
                    <label class="label"><?= __('Temporary commission') ?></label>
                </div>
            </div>
        </div>
    </div>
</div>
