<?php
/**
 * Copyright © 2019 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_MegaMenu extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package Magenest_MegaMenu
 */

namespace Magenest\MegaMenu\Model;

use Magento\Framework\Model\AbstractModel;
use Magento\Framework\DataObject\IdentityInterface;

/**
 * Class MegaMenu
 * @package Magenest\MegaMenu\Model
 *
 * @method string getMenuName()
 * @method string getIsActive()
 */
class MegaMenu extends AbstractModel implements IdentityInterface
{
    const CACHE_TAG = 'magenest_menu';

    /**
     * @var string
     */
    protected $_eventPrefix = 'magenest_menu';

    /**
     * @var string
     */
    protected $_eventObject = 'object';

    /**
     * @inheritdoc
     */
    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }

    /**
     * @inheritdoc
     */
    protected function _construct()
    {
        parent::_construct();
        $this->_init(\Magenest\MegaMenu\Model\ResourceModel\MegaMenu::class);
    }

    public function loadByAlias($alias, $storeId = 0)
    {
        $modelId = $this->getResource()->getIdByAlias($alias, $storeId);

        return parent::load($modelId);
    }

    public function afterSave()
    {
        $this->_cacheManager->clean($this->getIdentities());
        return parent::afterSave(); // TODO: Change the autogenerated stub
    }
}
