<?php
// @codingStandardsIgnoreFile
/**
 * @var Magenest\RewardPoints\Block\Adminhtml\Order\Creditmemo\Controls $block
 */
?>

<?php if ($block->canRefundToMgnRewardPoints()): ?>
    <div class="admin__field admin__field-option field-refund-mgn-reward-points" style="display: inline-block;">
        <input type="hidden" name="creditmemo[refund_mgn_reward_points_return_enable]" value="0">
        <input type="checkbox"
               class="admin__control-checkbox"
               name="creditmemo[refund_mgn_reward_points_return_enable]"
               value="1" id="creditmemo_mgn_reward_points_return_enable"
        />
        <label for="creditmemo_mgn_reward_points_return_enable" class="admin__field-label">
            <span><?= /* @escapeNotVerified */ __('Refund as Reward Points') ?></span>
        </label>
	    <label class="for-creditmemo_mgn_reward_points_return">
	        <input type="text"
	               name="creditmemo[refund_mgn_reward_points_return]"
	               value="<?= /* @escapeNotVerified */ $block->getReturnValue() ?>"
	               id="creditmemo_mgn_reward_points_return"
	               class="input-text admin__control-text not-negative-amount validate-greater-than-zero"
	               style="display: inline-block;padding-right: 50px;"
	        />
	    </label>
	    <label class="for-creditmemo_mgn_amount_points_return" style="position: relative;">
		    <input type="text"
		           value="<?= /* @escapeNotVerified */ $block->getReturnPointValue() ?>"
		           id="creditmemo_mgn_amount_points_return"
		           class="input-text admin__control-text not-negative-amount validate-greater-than-zero"
		           style="display: inline-block;padding-right: 50px; background-color: #f5f5f5 !important;"
		           disabled
		    />
	    </label>
        <script>
        require(['jquery'], function($) {
            $(function ($) {
                var pointValue = <?= $block->getPointValue() ?>;
                var upOrDown = '<?= $block->getUpOrDown() ?>';
                var toggleMgnRewardPointsRefundAmount = function (e) {
                    var refundReturn = $('#creditmemo_mgn_reward_points_return');
                    if ($(e.target).prop('checked')) {
                        refundReturn.prop('disabled', false);
                    } else {
                        refundReturn.prop('disabled', true);
                    }
                };
                var refundMgnRewardPointsEnable = $('#creditmemo_mgn_reward_points_return_enable');
                refundMgnRewardPointsEnable.change(toggleMgnRewardPointsRefundAmount);
                toggleMgnRewardPointsRefundAmount({target:refundMgnRewardPointsEnable});

                var reCalculatePoints = function (e) {
                    var refundAmount = $(e.target).val();
                    refundAmount = parseFloat(refundAmount);
                    if (refundAmount !== undefined) {
                        var pointAmount = refundAmount * pointValue;
                        if (upOrDown === 'up') {
                            pointAmount = Math.ceil(pointAmount);
                        } else {
                            pointAmount = Math.floor(pointAmount);
                        }
                        $('input#creditmemo_mgn_amount_points_return').val(pointAmount);
                    }
                    if (isNaN(refundAmount)) {
                        $('input#creditmemo_mgn_amount_points_return').val(0);
                    }
                };
                var refundRpAmount = $('#creditmemo_mgn_reward_points_return');
                refundRpAmount.keyup(reCalculatePoints);
            });
        });
        </script>
    </div>
<style>
	label.for-creditmemo_mgn_reward_points_return:after {
		content: '<?= $block->getCurrentCurrencySymbol() ?>';
		position: absolute;
		transform: translateX(-100%);
		display: inline-block;
		float: right;
		font-size: 1.4rem;
		line-height: 1.36;
		padding: 0.6rem 1rem 0.6rem;
	}
	label.for-creditmemo_mgn_amount_points_return:before {
		content: '\e625';
		font-family: Admin Icons;
	}
	label.for-creditmemo_mgn_amount_points_return:after {
		content: 'point(s)';
		transform: translateX(-100%);
		display: inline-block;
		float: right;
		font-size: 1.4rem;
		line-height: 1.36;
		padding: 0.6rem 1rem 0.6rem;
		color: #adadad;
	}
</style>

<script>
    require(
        [
            'jquery',
            'jquery/ui',
            'jquery/validate',
            'mage/translate',
            'Magento_Ui/js/lib/view/utils/async'
        ],
        function($){
        $(document).ready(function() {
            var refundValue = null;
            $('#creditmemo_mgn_reward_points_return').bind('input propertychange', function() {
                refundValue = $('#creditmemo_mgn_reward_points_return').val();
                if ($.isNumeric(refundValue) && refundValue > 0 || refundValue === '') {
                    $('.creditmemo_mgn_reward_points_return-error').remove();
                    return;
                }

                $('#creditmemo_mgn_reward_points_return-error').remove();
                var htmlEMsg;

                htmlEMsg = '<label for="creditmemo_mgn_reward_points_return" generated="true" class="creditmemo_mgn_reward_points_return-error mage-error" id="creditmemo_mgn_reward_points_return-error-mnc"><?= __('Please enter a number greater than 0 in this field.'); ?></label>';

                if ($('.creditmemo_mgn_reward_points_return-error').length === 0) {
                    $('.field-refund-mgn-reward-points').append(htmlEMsg);
                }
            });

            $('#edit_form button.submit-button').on('click', function(e) {
                if (!('#edit_form').valid) {
                    e.preventDefault();

                    refundValue = $('#creditmemo_mgn_reward_points_return').val();
                    if ($.isNumeric(refundValue) && refundValue > 0) return;

                    $('#creditmemo_mgn_reward_points_return-error').remove();
                    $('.creditmemo_mgn_reward_points_return-error').remove();
                    var htmlEMsg;

                    htmlEMsg = '<label for="creditmemo_mgn_reward_points_return" generated="true" class="creditmemo_mgn_reward_points_return-error mage-error" id="creditmemo_mgn_reward_points_return-error-mnc"><?= __('Please enter a number greater than 0 in this field. Please refresh page to try again.'); ?></label>';

                    $('.field-refund-mgn-reward-points').append(htmlEMsg);
                    $('#creditmemo_mgn_reward_points_return').prop('disabled', true);
                }
            });
        });
    });
</script>
<?php endif; ?>
