<?php
/**
 * Copyright © Magenest JSC. All rights reserved.
 *
 * Created by PhpStorm.
 * User: crist
 * Date: 22/11/2021
 * Time: 14:12
 */

namespace Magenest\CustomizePriceFilter\Model\Config\Backend\Serialized;

use Magento\Config\Model\Config\Backend\Serialized\ArraySerialized;
use Magento\Framework\Exception\LocalizedException;

class PriceOptions extends ArraySerialized
{
    public function beforeSave()
    {
        $value = $this->getValue();
        $previousOption = 0;
        foreach ($value as $key => $option) {
            if ($key == "__empty") {
                continue;
            }
            if ($option['price_option'] < $previousOption) {
                throw new LocalizedException(__("Price options must be arrange in ascending order. Details: option {$previousOption} and option {$option['price_option']}"));
            }
            $previousOption = $option['price_option'];
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}
