<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Vault\Api\Data\PaymentTokenInterface;
/** @var \Magenest\PaymentEPay\Block\Customer\CardRenderer $block */
$tokens = $block->getPaymentTokens();
?>
<?php if (count($tokens) !== 0) : ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Stored Payment Methods')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col card-number"><?= $block->escapeHtml(__('Card Number')) ?></th>
                <th scope="col" class="col card-type"><?= $block->escapeHtml(__('Type')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
                foreach ($tokens as $token):
                    $cardDetail = json_decode($token->getDetails());
                    ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
                        <span><?= $block->escapeHtml(__('ending')) ?></span><?=  $cardDetail->maskedCC ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col card-type">
                        <img style="width: 50px;" src="<?= /* @noEscape */ $block->getIconUrl($cardDetail->type) ?>"
                        >
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <form
                            class="form"
                            action="<?= $block->escapeUrl($block->getUrl('epay/cards/deleteaction')) ?>"
                            method="post"
                        >
                            <?= $block->getBlockHtml('formkey') ?>
                            <input
                                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                                value="<?= /* @noEscape */ $token->getData('public_hash') ?>"
                                type="hidden"/>
                            <button type="submit"
                                    class="action delete"
                                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                                        "content": "<?= $block->escapeHtml(__('Are you sure you want to delete this card: %1?', $cardDetail->maskedCC)) ?>"
                                    }
                                }'>
                                <span><?= $block->escapeHtml(__('Delete')) ?></span>
                            </button>
                        </form>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php elseif (!$block->isExistsCustomerTokens()) : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have no stored payment methods.')) ?></span></div>
<?php endif ?>
