<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="toolbar-filter">
    <p class="toolbar-amount" id="toolbar-amount">
        <?= $block->escapeHtml(
            __(
                '%1 Items',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
        ) ?>
    </p>
    <p class="filter-mobile mobile-device">
        <?= __('Filter products') ?>
    </p>
</div>

<?php $scriptString = <<<script
    require([
        'jquery'
    ], function($){
        $(document).on('click', '.filter-mobile', function () {
            $('.sidebar.sidebar-main').addClass('filter-active')
            $('body').addClass('filter-show')
        })

        $(document).mouseup(function (e) {
            var container = $('.block.filter.mgs-filter');
            if (!container.is(e.target) && container.has(e.target).length === 0) {
                container.parents().removeClass('filter-active')
                $('body').removeClass('filter-show')
            }
        });

        $(document).on('click', '.close-filter', function () {
            $('.sidebar.sidebar-main').removeClass('filter-active')
            $('body').removeClass('filter-show')
        })
    });
script;
    ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
