<?php
/**
 * Created by PhpStorm.
 * User: doanhcn2
 * Date: 28/03/2019
 * Time: 11:13
 */

namespace Magenest\Slider\Ui\Component\Listing\Column;


use Magento\Ui\Component\Listing\Columns\Column;

class SliderStatus extends Column
{
    public function prepareDataSource(array $dataSource)
    {
        parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
        if (isset($dataSource['data']['items'])) {
            foreach($dataSource['data']['items'] as & $item) {
                if (isset($item['status'])) {
                    switch ($item['status']) {
                        case 0:
                            $class = "grid-severity-critical";
                            $value = 'OFF';
                            break;
                        case 1:
                            $class = "grid-severity-notice";
                            $value = 'ON';
                            break;
                    }
                }

                $item[$this->getData('name')] = '<span	class="'.$class.'"><span>'.$value.'</span></span>';
            }
        }
        return $dataSource;
    }
}