<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/** @var \Aheadworks\AdvancedReports\Block\View\Grid $block */
$numColumns = sizeof($block->getColumns());
?>
<?php if ($block->getCollection()): ?>

    <?php if ($block->canDisplayContainer()): ?>
    <div id="<?= $block->getId() ?>" data-grid-id="<?= $block->getId() ?>">
        <?php else: ?>
            <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
        <?php endif; ?>

        <div class="admin__data-grid-wrap">
            <?php if ($block->getGridCssClass()): ?>
                <table class="<?= $block->getGridCssClass() ?> data-grid" id="<?= $block->getId() ?>_table">
                    <!-- Rendering column set -->
                    <?= $block->getChildHtml('grid.columnSet'); ?>
                </table>
            <?php else: ?>

                <table class="data-grid" id="<?= $block->getId() ?>_table">
                    <!-- Rendering column set -->
                    <?= $block->getChildHtml('grid.columnSet'); ?>
                </table>

                <?php if ($block->getChildBlock('grid.bottom.links')): ?>
                    <?= $block->getChildHtml('grid.bottom.links') ?>
                <?php endif; ?>

            <?php endif ?>
        </div>
        <?php if ($block->getPagerVisibility() && $block->getCollection()->getLastPageNumber() > 1): ?>
            <div class="admin__data-grid-pager-wrap">
                <select name="<?= $block->getVarNameLimit() ?>"
                        id="<?= $block->getHtmlId()?>_page-limit"
                        onchange="<?= $block->getJsObjectName() ?>.loadByElement(this)" <?= $block->getUiId('per-page') ?>
                        class="admin__control-select">
                    <option value="20"<?php if ($block->getCollection()->getPageSize() == 20): ?>
                        selected="selected"<?php endif; ?>>20
                    </option>
                    <option value="30"<?php if ($block->getCollection()->getPageSize() == 30): ?>
                        selected="selected"<?php endif; ?>>30
                    </option>
                    <option value="50"<?php if ($block->getCollection()->getPageSize() == 50): ?>
                        selected="selected"<?php endif; ?>>50
                    </option>
                    <option value="100"<?php if ($block->getCollection()->getPageSize() == 100): ?>
                        selected="selected"<?php endif; ?>>100
                    </option>
                    <option value="200"<?php if ($block->getCollection()->getPageSize() == 200): ?>
                        selected="selected"<?php endif; ?>>200
                    </option>
                </select>
                <label for="<?= $block->getHtmlId()?>_page-limit"
                       class="admin__control-support-text"><?= __('per page') ?></label>
                <div class="admin__data-grid-pager">
                    <?php $_curPage = $block->getCollection()->getCurPage() ?>
                    <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>

                    <?php if ($_curPage > 1): ?>
                        <button class="action-previous"
                                type="button"
                                onclick="<?= $block->getJsObjectName() ?>.setPage('<?=($_curPage - 1) ?>');return false;">
                            <span><?= __('Previous page') ?></span>
                        </button>
                    <?php else: ?>
                        <button type="button" class="action-previous disabled"><span><?= __('Previous page') ?></span></button>
                    <?php endif; ?>

                    <input type="text"
                           id="<?= $block->getHtmlId()?>_page-current"
                           name="<?= $block->getVarNamePage() ?>"
                           value="<?= $_curPage ?>"
                           class="admin__control-text"
                           onkeypress="<?= $block->getJsObjectName() ?>.inputPage(event, '<?= $_lastPage ?>')" <?= $block->getUiId('current-page') ?> />

                    <label class="admin__control-support-text" for="<?= $block->getHtmlId()
                    ?>_page-current">
                        <?= __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                    </label>
                    <?php if ($_curPage < $_lastPage): ?>
                        <button title="<?= __('Next page') ?>"
                                class="action-next"
                                onclick="<?= $block->getJsObjectName() ?>.setPage('<?=($_curPage + 1) ?>');return false;">
                            <span><?= __('Next page') ?></span>
                        </button>
                    <?php else: ?>
                        <button type="button" class="action-next disabled"><span><?= __('Next page') ?></span></button>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif ?>
        <?php if ($block->canDisplayContainer()): ?>
    </div>
    <script>
        var deps = ['mage/adminhtml/grid'];

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false): ?>
        deps.push('Magento_Sales/order/create/form');
        <?php endif; ?>

        require(deps, function(){
            <?= $block->getJsObjectName() ?> = new varienGrid('<?= $block->getId() ?>', '<?= $block->getGridUrl() ?>', '<?= $block->getVarNamePage() ?>', '<?= $block->getVarNameSort() ?>', '<?= $block->getVarNameDir() ?>', '<?= $block->getVarNameFilter() ?>');
            <?= $block->getJsObjectName() ?>.useAjax = <?= $block->getUseAjax() ? 'true' : 'false' ?>;
            <?php if ($block->getRowClickCallback()): ?>
            <?= $block->getJsObjectName() ?>.rowClickCallback = <?= $block->getRowClickCallback() ?>;
            <?php endif; ?>
            <?php if ($block->getCheckboxCheckCallback()): ?>
            <?= $block->getJsObjectName() ?>.checkboxCheckCallback = <?= $block->getCheckboxCheckCallback() ?>;
            <?php endif; ?>
            <?php if ($block->getSortableUpdateCallback()): ?>
            <?= $block->getJsObjectName() ?>.sortableUpdateCallback = <?= $block->getSortableUpdateCallback()?>;
            <?php endif; ?>
            <?= $block->getJsObjectName() ?>.bindSortable();
            <?php if ($block->getRowInitCallback()): ?>
            <?= $block->getJsObjectName() ?>.initRowCallback = <?= $block->getRowInitCallback() ?>;
            <?= $block->getJsObjectName() ?>.initGridRows();
            <?php endif; ?>
            <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()): ?>
            <?= $block->getChildBlock('grid.massaction')->getJavaScript() ?>
            <?php endif ?>
            <?= $block->getAdditionalJavaScript(); ?>
        });
    </script>
<?php endif; ?>

    <?php if ($block->getChildBlock('grid.js')): ?>
        <?= $block->getChildHtml('grid.js'); ?>
    <?php endif; ?>

<?php endif ?>

