<?php
/**
 * @var $block Magenest\MapList\Block\Adminhtml\Brand\Validate
 */
$maxSize = floatval(ini_get('post_max_size'));
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($,modalAlert) {
        'use strict';

        function checkImage(file) {
            var maxSize = <?= $maxSize ?>;
            //Tested in Firefox and Google Chorme
            var sizee = file.size; //file size in bytes
            sizee = sizee / 1024; //file size in Kb
            sizee = sizee / 1024; //file size in Mb

            if (sizee > maxSize) {
                modalAlert({
                    title: 'File Error',
                    content: 'Maximum File Size Is Less Than ' + maxSize + 'MB',
                    actions: {
                        always: function () {
                        }
                    }
                });
                return false;
            }
            var fileType = file["type"];
            var ValidImageTypes = ["image/gif", "image/jpeg", "image/png","image/jpeg"];
            if ($.inArray(fileType, ValidImageTypes) === -1) {
                modalAlert({
                    title: 'File Error',
                    content: 'Photos should be saved as JPG, PNG, GIF, JPEG',
                    actions: {
                        always: function () {
                        }
                    }
                });
                return false;
            }
            return true;
        }

        var urllogo = "<?= $block->getLogo(); ?>";
        if (urllogo) {
            var table_html_logo = "<div class='image item base-image' id='image-logo' data-role='image'>" +
                "<div class='product-image-wrapper' style='overflow: -moz-hidden-unscrollable;'>" +
                "<img alt='' id='imagelogo'  class='product-image'  src='" + urllogo + "' />" +
                "<div class='actions'>" +
                "<button id='deletelogo'  type='button' class='action-remove' data-role='delete-button' title='Delete image'>" +
                "<span>Delete image</span>" +
                "</button>" +
                "<div class='draggable-handle'></div>" +
                "</div>" +
                "<div class='image-fade'><span>Hidden</span></div>" +
                "</div>" +
                "</div>";
            $('#logo-brand').before(table_html_logo);
            $('#logo-brand').hide();
        }

        $(document).on('click', '#deletelogo', function () {
            document.getElementById('magenest-upload-image-logo').value = "";
            var url = '<?php  echo $block->getUrl('maplist/brand/uploadlogo');?>';
            var param = {
                id: $('#brand_brand_id').val()
            };
            $.ajax({
                showLoader: true,
                url: url,
                data: param,
                type: "POST",
                dataType: 'json',
                cache: false
            }).done(function (data) {
            });
            $('#image-logo').remove();
            $('#logo-brand').show();
        });

        $('#magenest-upload-image-logo').on('change', function () {
            var file = document.getElementById('magenest-upload-image-logo').files[0];
            var check = checkImage(file);
            if (check === true) {
                var table_html_logo = "<div class='image item base-image' id='image-logo' data-role='image'>" +
                    "<div class='product-image-wrapper' style='overflow: -moz-hidden-unscrollable;'>" +
                    "<img alt='' id='imagelogo'  class='product-image' />" +
                    "<div class='actions'>" +
                    "<button id='deletelogo' type='button' class='action-remove' data-role='delete-button' title='Delete image'>" +
                    "<span>Delete image</span>" +
                    "</button>" +
                    "<div class='draggable-handle'></div>" +
                    "</div>" +
                    "<div class='image-fade'><span>Hidden</span></div>" +
                    "</div>" +
                    "</div>";
                $('#logo-brand').before(table_html_logo);
                $('#logo-brand').hide();
                if (file) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        jQuery('#imagelogo').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(file);
                }
            }
            else{
                document.getElementById('magenest-upload-image-logo').value = "";
            }
        });
    });

</script>
