<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Customer\Block\Address\Edit $block */

$_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company');
$_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone');
$_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax');
$cityId = $block->getAddress()->getCustomAttribute('city_id') ? $block->getAddress()->getCustomAttribute('city_id')->getValue(): '';
$district = $block->getAddress()->getCustomAttribute('district') ? $block->getAddress()->getCustomAttribute('district')->getValue(): '';
$districtId = $block->getAddress()->getCustomAttribute('district_id') ? $block->getAddress()->getCustomAttribute('district_id')->getValue(): '';
$ward = $block->getAddress()->getCustomAttribute('ward') ? $block->getAddress()->getCustomAttribute('ward')->getValue(): '';
$wardId = $block->getAddress()->getCustomAttribute('ward_id') ? $block->getAddress()->getCustomAttribute('ward_id')->getValue(): '';
?>
<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city_id">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('City') ?></span>
            </label>
            <div class="control">
                <select id="city_id" name="city_id"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                        class="validate-select district_id">
                    <option value=""><?= $block->escapeHtml(__('Please select a city.')) ?></option>
                </select>
                <input type="text"
                       id="city"
                       name="city"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text" <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>/>
            </div>
        </div>
        <div class="field district required">
            <label class="label" for="district_id">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('district') ?></span>
            </label>
            <div class="control">
                <select id="district_id" name="district_id"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('district') ?>"
                        class="validate-select district_id">
                    <option value=""><?= $block->escapeHtml(__('Please select a district.')) ?></option>
                </select>
                <input type="text"
                       id="district"
                       name="district"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($district) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('district') ?>"
                       class="input-text"/>
            </div>
        </div>
        <div class="field ward required">
            <label class="label" for="ward_id">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('ward') ?></span>
            </label>
            <div class="control">
                <select id="ward_id" name="ward_id"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('ward') ?>"
                        class="validate-select ward_id">
                    <option value=""><?= $block->escapeHtml(__('Please select a ward')) ?></option>
                </select>
                <input type="text"
                       id="ward"
                       name="ward"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($ward) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('ward') ?>"
                       class="input-text"/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required">
            <div class="control">
                <input type="hidden" name="country_id" value="VN" title="Country" id="country" class="input-text">
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox checkbox-custom">
                <label class="label" for="primary_billing">
                    <span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox checkbox-custom">
                <label class="label" for="primary_shipping">
                    <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        ".form-address-edit": {
            "Magenest_Directory/js/field-updater": {
                "form": "#form-validate",
                "defaultCity": "<?= (int) $cityId ?>",
                "defaultDistrict": "<?= (int) $districtId ?>",
                "defaultWard": "<?= (int) $wardId ?>",
                "dataJson": <?= /* @noEscape */ $this->helper(\Magenest\Directory\Helper\Data::class)->getDataJson() ?>
            }
        }
    }
</script>
