<?php
/**
 * Created by PhpStorm.
 * User: doanhcn2
 * Date: 29/03/2019
 * Time: 10:39
 * @var \Magenest\Slider\Block\Widget\SliderView $block;
 */

$baseUrl = $block->getBaseUrl();
$sliderData = $block->getSliderData();
$childSliderData = $block->getChildSliderData();
$sliderId = $sliderData['id'];
$sliderItem = $sliderData["items"][0];
?>
<?php if($sliderData['customCss']) : ?>
    <style><?= $sliderData['customCss'] ?></style>
<?php endif; ?>

<div class="magenest-banner <?= $sliderItem['itemCustomClass'] ?>" id="magenest_banner_<?= $sliderId; ?>"
     style=" <?php if($sliderItem['paddingTop']): echo('padding-top: '.$sliderItem['paddingTop'].'px;'); endif; ?>
             <?php if($sliderItem['paddingBottom']): echo('padding-bottom: '.$sliderItem['paddingBottom'].'px;'); endif; ?>
             <?php if($sliderItem['paddingLeft']): echo('padding-left: '.$sliderItem['paddingLeft'].'px;'); endif; ?>
             <?php if($sliderItem['paddingRight']): echo('padding-right: '.$sliderItem['paddingRight'].'px;'); endif; ?>
             <?php if($sliderItem['marginTop']): echo('margin-top: '.$sliderItem['marginTop'].'px;'); endif; ?>
             <?php if($sliderItem['marginBottom']): echo('margin-bottom: '.$sliderItem['marginBottom'].'px;'); endif; ?>
             <?php if($sliderItem['marginLeft']): echo('margin-left: '.$sliderItem['marginLeft'].'px;'); endif; ?>
             <?php if($sliderItem['marginRight']): echo('margin-right: '.$sliderItem['marginRight'].'px;'); endif; ?>
             <?php if(isset($sliderItem['bgImage']) && $sliderItem['bgImage']): echo('background-image: url('. $baseUrl . $sliderItem['bgImage'].');'); endif; ?>
             <?php if(isset($sliderItem['bgPosition']) && $sliderItem['bgPosition']): echo('background-position: '.$sliderItem['bgPosition'].';'); endif; ?>
             <?php if(isset($sliderItem['bgSize']) && $sliderItem['bgSize']): echo('background-size: '.$sliderItem['bgSize'].';'); endif; ?>
             <?php if(isset($sliderItem['bgRepeat']) && $sliderItem['bgRepeat']): echo('background-repeat: '.$sliderItem['bgRepeat'].';'); endif; ?>">
    <div class="magenest-banner-content <?= 'animated '.$sliderItem['contentAnimation']; ?> <?php if($sliderItem['contentAnimationDelay']): echo('mgn-animation-delay'); endif; ?>"
         style=" <?php if($sliderItem['contentPaddingTop']): echo('padding-top: '.$sliderItem['contentPaddingTop'].'px;'); endif; ?>
                 <?php if($sliderItem['contentPaddingBottom']): echo('padding-bottom: '.$sliderItem['contentPaddingBottom'].'px;'); endif; ?>
                 <?php if($sliderItem['contentPaddingLeft']): echo('padding-left: '.$sliderItem['contentPaddingLeft'].'px;'); endif; ?>
                 <?php if($sliderItem['contentPaddingRight']): echo('padding-right: '.$sliderItem['contentPaddingRight'].'px;'); endif; ?>
                 <?php if($sliderItem['contentMarginTop']): echo('margin-top: '.$sliderItem['contentMarginTop'].'px;'); endif; ?>
                 <?php if($sliderItem['contentMarginBottom']): echo('margin-bottom: '.$sliderItem['contentMarginBottom'].'px;'); endif; ?>
                 <?php if($sliderItem['contentMarginLeft'] && $sliderItem['contentPosition'] != 'center'): echo('margin-left: '.$sliderItem['contentMarginLeft'].'px;'); endif; ?>
                 <?php if($sliderItem['contentMarginRight'] && $sliderItem['contentPosition'] != 'center'): echo('margin-right: '.$sliderItem['contentMarginRight'].'px;'); endif; ?>
                 <?php if($sliderItem['contentPosition'] != 'center'):
                     $maxWidth = (int)$sliderItem['contentMarginLeft'] + (int)$sliderItem['contentMarginRight'];
                     echo ('max-width: calc(100% - '.$maxWidth.'px);');
                 endif; ?>
                 <?php if($sliderItem['contentWidth'] && $sliderItem['contentWidthUnit']): echo('width: '.$sliderItem['contentWidth'].$sliderItem['contentWidthUnit'].';'); endif; ?>
                 <?php if($sliderItem['contentHeight'] && $sliderItem['contentHeightUnit']): echo('height: '.$sliderItem['contentHeight'].$sliderItem['contentHeightUnit'].';'); endif; ?>
                 <?php if($sliderItem['contentPosition'] == 'right'):
                     echo('float: right;');
                 elseif($sliderItem['contentPosition'] == 'center'):
                     echo('float: none; margin-left: auto; margin-right: auto;');
                 endif; ?>
                 <?php if($sliderItem['contentBgColor'] && $sliderItem['contentOpacity']): echo('background-color: '.$block->hex2rgba($sliderItem['contentBgColor'], $sliderItem['contentOpacity']).';'); endif; ?>
                 <?php if($sliderItem['contentAnimationDelay']): echo('--animation-delay:'.$sliderItem['contentAnimationDelay'].'s;'); endif; ?>">

        <!-- Content Box -->
        <?php foreach ($sliderItem['blocks'] as $contentBox) : ?>
            <!-- Button -->
            <?php if($contentBox['type']=='button'):?>
                <div class="content-box content-box--button content-box--<?= $contentBox['position'] ?> <?= $contentBox['customClass'] ?>">
                    <?php
                    $btnUrl = $contentBox['customLink'];
                    $btnColor = $contentBox['textColor'] ? $contentBox['textColor'] : '#f26321';
                    $btnColorHover = $contentBox['textColorHover'] ? $contentBox['textColorHover'] : $btnColor;
                    $btnBgColor = $contentBox['bgColor'] ? $contentBox['bgColor'] : 'transparent';
                    $btnBgColorHover = $contentBox['bgColorHover'] ? $contentBox['bgColorHover'] : $btnBgColor;
                    $btnBorderColor = $contentBox['borderColor'] ? $contentBox['borderColor'] : 'transparent';
                    $btnBorderColorHover = $contentBox['borderColorHover'] ? $contentBox['borderColorHover'] : $btnBgColor;
                    ?>
                    <a href="<?= $btnUrl ?>" class="magenest-button <?= 'animated '.$contentBox['animation'] ?> <?php if($contentBox['animationDelay']): echo('mgn-animation-delay'); endif; ?>"
                       style=" <?php if($contentBox['width'] && $contentBox['widthUnit']): echo('width: '.$contentBox['width'].$contentBox['widthUnit'].';'); endif; ?>
                       <?php if($contentBox['paddingTop']): echo('padding-top: '.$contentBox['paddingTop'].'px;'); endif; ?>
                       <?php if($contentBox['paddingBottom']): echo('padding-bottom: '.$contentBox['paddingBottom'].'px;'); endif; ?>
                       <?php if($contentBox['paddingLeft']): echo('padding-left: '.$contentBox['paddingLeft'].'px;'); endif; ?>
                       <?php if($contentBox['paddingRight']): echo('padding-right: '.$contentBox['paddingRight'].'px;'); endif; ?>
                       <?php if($contentBox['marginTop']): echo('margin-top: '.$contentBox['marginTop'].'px;'); endif; ?>
                       <?php if($contentBox['marginBottom']): echo('margin-bottom: '.$contentBox['marginBottom'].'px;'); endif; ?>
                       <?php if($contentBox['marginLeft']): echo('margin-left: '.$contentBox['marginLeft'].'px;'); endif; ?>
                       <?php if($contentBox['marginRight']): echo('margin-right: '.$contentBox['marginRight'].'px;'); endif; ?>
                       <?php if($contentBox['fontSize']): echo('font-size:'.$contentBox['fontSize'].'px;'); endif; ?>
                       <?php if($contentBox['animationDelay']): echo('--animation-delay:'.$contentBox['animationDelay'].'s;'); endif; ?>
                               --color: <?= $btnColor ?>;
                               --color-hover: <?= $btnColorHover ?>;
                               --bg: <?= $btnBgColor ?>;
                               --bg-hover: <?= $btnBgColorHover ?>;
                               --border: <?= $btnBorderColor ?>;
                               --border-hover: <?= $btnBorderColorHover ?>;">
                        <?= $contentBox['content'] ?>
                    </a>
                </div>
                <!-- END Button -->
                <!-- Text -->
            <?php elseif ($contentBox['type']=='text'):?>
                <div class="content-box content-box--text content-box--<?= $contentBox['position'] ?> <?= $contentBox['customClass'] ?> <?= 'animated '.$contentBox['animation'] ?> <?php if($contentBox['animationDelay']): echo('mgn-animation-delay'); endif; ?>"
                     style=" <?php if($contentBox['width'] && $contentBox['widthUnit']): echo('width: '.$contentBox['width'].$contentBox['widthUnit'].';'); endif; ?>
                     <?php if($contentBox['textAlign']): echo('text-align: '.$contentBox['textAlign'].';'); endif; ?>
                     <?php if($contentBox['textColor']): echo('color: '.$contentBox['textColor'].';'); endif; ?>
                     <?php if($contentBox['paddingTop']): echo('padding-top: '.$contentBox['paddingTop'].'px;'); endif; ?>
                     <?php if($contentBox['paddingBottom']): echo('padding-bottom: '.$contentBox['paddingBottom'].'px;'); endif; ?>
                     <?php if($contentBox['paddingLeft']): echo('padding-left: '.$contentBox['paddingLeft'].'px;'); endif; ?>
                     <?php if($contentBox['paddingRight']): echo('padding-right: '.$contentBox['paddingRight'].'px;'); endif; ?>
                     <?php if($contentBox['marginTop']): echo('margin-top: '.$contentBox['marginTop'].'px;'); endif; ?>
                     <?php if($contentBox['marginBottom']): echo('margin-bottom: '.$contentBox['marginBottom'].'px;'); endif; ?>
                     <?php if($contentBox['marginLeft']): echo('margin-left: '.$contentBox['marginLeft'].'px;'); endif; ?>
                     <?php if($contentBox['marginRight']): echo('margin-right: '.$contentBox['marginRight'].'px;'); endif; ?>
                     <?php if($contentBox['fontSize']): echo('font-size:'.$contentBox['fontSize'].'px;'); endif; ?>
                     <?php if($contentBox['animationDelay']): echo('--animation-delay:'.$contentBox['animationDelay'].'s;'); endif; ?>">
                    <h3><?= $contentBox['content'] ?></h3>
                </div>
                <!-- END Text -->
                <!-- HTML -->
            <?php elseif ($contentBox['type']=='html'):?>
                <div class="content-box content-box--html content-box--<?= $contentBox['position'] ?> <?= $contentBox['customClass'] ?> <?= 'animated '.$contentBox['animation'] ?> <?php if($contentBox['animationDelay']): echo('mgn-animation-delay'); endif; ?>"
                     style=" <?php if($contentBox['width'] && $contentBox['widthUnit']): echo('width: '.$contentBox['width'].$contentBox['widthUnit'].';'); endif; ?>
                     <?php if($contentBox['paddingTop']): echo('padding-top: '.$contentBox['paddingTop'].'px;'); endif; ?>
                     <?php if($contentBox['paddingBottom']): echo('padding-bottom: '.$contentBox['paddingBottom'].'px;'); endif; ?>
                     <?php if($contentBox['paddingLeft']): echo('padding-left: '.$contentBox['paddingLeft'].'px;'); endif; ?>
                     <?php if($contentBox['paddingRight']): echo('padding-right: '.$contentBox['paddingRight'].'px;'); endif; ?>
                     <?php if($contentBox['marginTop']): echo('margin-top: '.$contentBox['marginTop'].'px;'); endif; ?>
                     <?php if($contentBox['marginBottom']): echo('margin-bottom: '.$contentBox['marginBottom'].'px;'); endif; ?>
                     <?php if($contentBox['marginLeft']): echo('margin-left: '.$contentBox['marginLeft'].'px;'); endif; ?>
                     <?php if($contentBox['marginRight']): echo('margin-right: '.$contentBox['marginRight'].'px;'); endif; ?>">
                    <?= $contentBox['content'] ?>
                </div>
            <?php endif;?>
            <!-- END HTML -->
        <?php endforeach; ?>
        <!-- END Content Box -->

    </div>
</div>
