<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Sales\Block\Order\Comments
 * @see \Magento\Sales\Block\Order\Comments
 */
?>
<?php if ($block->hasComments()) : ?>
    <div class="block block-order-details-comments">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Message')) ?></strong></div>
        <dl class="block-content">
            <?php foreach ($block->getComments() as $_commentItem) : ?>
                <dd class="comment-content"><?= $block->escapeHtml($_commentItem->getComment()) ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php endif;?>
