<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
/**
 * @var Firebear\ImportExport\Block\Adminhtml\Import\History\Before $block
 */
?>
<div id="messages">
    <div class="messages">
        <div class="message message-notice">
            <div>Số dư hiện tại của tài khoản là <span class="account-balance price"><?= $block->getAccountBalance() ?></span></div>
            <a href="" class="account-balance-update">Cập nhật số dư</a>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery'], function($){
        $(document).ready(function() {
            $('.account-balance-update').on('click', function () {
                event.preventDefault();
                event.stopImmediatePropagation();
                $.ajax({
                    url: "<?= $block->getUrl('affiliate/transaction/balanceUpdate') ?>",
                    type: 'get',
                    data: [],
                    showLoader: true,
                    success: function (response) {
                        if (response.success) {
                            $('.account-balance').html(response.balance);
                        } else {
                            alert(response.message);
                        }
                    }
                })
            });
        });
    });
</script>
