<?php
/**
 * @var $block \FishPig\WordPress\Block\Post\ListPostSlider
 */
$isActive = $block->getRequest()->getParam('mode') !== 'featured_last_week';
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
<h1 class="heading"><?= $block->escapeHtml(__('Featured posts')) ?></h1>
<div class="heading-link">
    <ul>
        <li class="<?= $isActive  ? 'active' : '' ?>"><a href="?mode=news"><?= $block->escapeHtml(__('News')) ?></a></li>
        <li class="<?= !$isActive ? 'active' : '' ?>"><a href="?mode=featured_last_week"><?= $block->escapeHtml(__('Featured last week')) ?></a></li>
    </ul>
</div>
<div class="blog-slider-wrapper">
    <?php foreach ($posts as $post): ?>
    <div class="item item-post">
        <div class="image-blog slider-posts">
            <div class="item">
            <?php if ($image = $post->getImage()): ?>
                <?php $imageUrl = $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(600, null) : '' ?>

                    <img src="<?= $block->escapeUrl($imageUrl) ?>" alt="<?= $block->escapeHtml($post->getName()) ?>" jsname="HiaYvf" jsaction="load:XAeZkd;"
                         class="n3VNCb" data-noaft="1">
            <?php else: ?>
                <img src="<?= $block->escapeUrl($block->getDefaultImage()) ?>" alt="<?= $block->escapeHtml($post->getName()) ?>" jsname="HiaYvf" jsaction="load:XAeZkd;"
                     class="n3VNCb" data-noaft="1">
            <?php endif; ?>
            </div>
        </div>
        <div class="info-blog">
            <div class="post-title">
                <a class="post-item-link" href="<?= $block->escapeUrl($post->getUrl()) ?>"><?= $post->getPostTitle() ?></a>
            </div>
            <div class="post-excerpt">
                <p><?= $post->getExcerpt(60) ?></p>
            </div>
            <div class="date-post"><?= $post->getPostDate("d/m/Y") ?></div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "FishPig_WordPress/js/slider-blog": {}
        }
    }
</script>
