<?php

/** @var Magenest\SocialLogin\Block\Comment $block */
if ($block->enableComment()) :
    ?>

    <div id="fb-root"></div>
    <?php $scriptString = <<<script
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId={$block->getFacebookAppId()}";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      script;
    ?>
    <?= isset($secureRenderer) ? $secureRenderer->renderTag('script', [], $scriptString, false) : '<script>' . $scriptString . '</script>' ?>
    <div class="fb-comments" data-href="<?= $block->getUrlCurrent(); ?>" data-numposts="7"></div>

<?php endif; ?>
