<?php


$_element = $block->getElement();
?>

<div class="commission-tree">
    <fieldset id="<?= $_element->getHtmlId() ?>" class="fieldset">
        <legend class="legend">
            <span><?= /* @escapeNotVerified */ $_element->getLegend() ?></span>
        </legend>
        <br>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice"><?= $block->escapeHtml($_element->getComment()) ?></div>
            </div>
        <?php endif; ?>
        <div class="commission-tree-wrapper">
            <?= $_element->getChildrenHtml() ?>
        </div>
    </fieldset>
</div>
