<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
?>
<?php
$wishlstViewModel = $block->getData('wishlistDataViewModel');
?>
<?php if ($wishlstViewModel->isAllow()): ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <div class="block-title">
            <a class="" href="<?= $block->getUrl('wishlist') ?>"><span><strong role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></strong></span></a></strong>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter">.....</span>
            <!-- /ko -->
        </div>
        <div class="block-content">
            <strong class="subtitle"><?= $block->escapeHtml(__('Last Added Items')) ?></strong>
            <!-- ko if: wishlist().counter -->
            <div class="block-product-inner">
                <ol class="product-items no-display"
                    id="wishlist-sidebar"
                    data-bind="foreach: wishlist().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="text: product_name"></span>
                                    </a>
                                </strong>
                                <div class="price-inner" data-bind="html: product_price"></div>
                                <!-- ko if: discount_percent -->
                                <div class="discount-item" data-bind="text: discount_percent"></div>
                                <!-- /ko -->
                            </div>
                        </div>
                    </li>
                </ol>
            </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
            <div class="empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
