<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 * @var \FishPig\WordPress\Block\Post\View $block
 */
?>
<?php if ($post = $block->getPost()): ?>
    <?php if (!$post->isViewableForVisitor()): ?>
        <?= $block->getPasswordProtectHtml() ?>
    <?php else: ?>
        <div class="post-view">
        <div class="post-meta">
            <div class="post-date post-meta-item"><?= $block->formatDateVietNam($post->getPostDate("d/m/Y")) ?></div>
        </div>
        <div class="post-entry">
                <?php if ($image = $post->getImage()): ?>
                    <?php $imageUrl =  $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(1200, null) : ''?>
                    <div class="post-image">
                        <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getPostTitle()) ?>"><img src="<?= $imageUrl ?>" alt="<?= $block->escapeHtml($post->getPostTitle()) ?>"/></a>
                    </div>
                <?php endif; ?>
                <?php if (($content = trim($post->getContent())) !== ''): ?>
                    <div class="post-content"><?= $content ?></div>
                <?php endif; ?>
            </div>
    <?php endif; ?>
    <?= $block->getChildHtml('recommender') ?>
    </div>
<?php endif; ?>
