<?php
/**
 * @var $block FishPig\WordPress\Block\Post
 */
?>

<?php $recommderList = $block->getRecommendPost(3) ?>
<div class="related-post">
    <h5><?= __('Recommend Post') ?></h5>
    <ul>
    <?php foreach ($recommderList as $item): ?>
        <li style="display:inline">
            <a href="<?= $block->escapeUrl($item->getUrl()) ?>" class="title" title="<?= $block->escapeHtml($item->getPostTitle()) ?>">
                <p><?= $item->getPostTitle() ?></p>
                <p><?= $item->getExcerpt(60) ?></p>
                <?php if ($image = $item->getImage()): ?>
                    <?php $imageUrl = $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(600, null) : '' ?>
                    <div class="item">
                        <img src="<?= $block->escapeUrl($imageUrl) ?>" alt="<?= $block->escapeHtml($item->getName()) ?>" jsname="HiaYvf" jsaction="load:XAeZkd;" class="n3VNCb" data-noaft="1" style="width: 435px; height: 290px; margin: 0px;">
                    </div>
                <?php else: ?>
                    <span class="empty"></span>
                <?php endif; ?>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
