<?php
/** @var \Magenest\SocialLogin\Block\Adminhtml\SocialAccount\Monitor $block */
?>
<div class="social-login-monitor">
    <div class="social-login-chart">
        <?= $block->getChildHtml('social_login_chart') ?>
    </div>
    <div class="top-social-login">
        <?= $block->getChildHtml('top_social_login') ?>
    </div>
    <div class="other-connection">
        <?= $block->getChildHtml('other_connections') ?>
    </div>
</div>