<?php
/**
 * Created by PhpStorm.
 * User: hiennq
 * Date: 9/11/16
 * Time: 09:59
 */

namespace Magenest\Promobar\Setup;

use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
    /**
     * Installs data for a module
     *
     * @param ModuleDataSetupInterface $setup
     * @param ModuleContextInterface $context
     * @return void
     */
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;

        $installer->startSetup();

        $tableName = $installer->getTable("magenest_promobar_button");
        if ($installer->getConnection()->isTableExists($tableName)) {
            $data = [
                [
                    'button_id' => 1,
                    'title' => 'Red Square Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"0","top_left":"0","bottom_left":"0","top_right":"0","bottom_right":"0","padding_top":"8","padding_left":"20"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => null,
                    'border_style' => 'none',
                    'border_width' => '1',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 2,
                    'title' => 'Red Square Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"0","top_left":"0","bottom_left":"0","top_right":"0","bottom_right":"0","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => '#f65e5e',
                    'hover_color_button' => '#ffffff',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 3,
                    'title' => 'Red Corner Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"8","top_left":"8","bottom_left":"8","top_right":"8","bottom_right":"8","padding_top":"8","padding_left":"20"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => null,
                    'border_style' => 'none',
                    'border_width' => '1',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null
                ],
                [
                    'button_id' => 4,
                    'title' => 'Red Corner Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"8","top_left":"8","bottom_left":"8","top_right":"8","bottom_right":"8","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => '#f65e5e',
                    'hover_color_button' => '#ffffff',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 5,
                    'title' => 'Red Rounded Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"20","top_left":"20","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"8","padding_left":"20"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => null,
                    'border_style' => 'none',
                    'border_width' => '1',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 6,
                    'title' => 'Red Rounded Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"20","top_left":"20","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#f65e5e',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => '#f65e5e',
                    'hover_color_button' => '#ffffff',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 7,
                    'title' => 'Red Square Light Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"0","top_left":"0","bottom_left":"0","top_right":"0","bottom_right":"0","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 8,
                    'title' => 'Red Square Light Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"0","top_left":"0","bottom_left":"0","top_right":"0","bottom_right":"0","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => '#ffffff',
                    'hover_color_button' => '#f65e5e',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 9,
                    'title' => 'Red Corner Light Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"8","top_left":"8","bottom_left":"8","top_right":"8","bottom_right":"8","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 10,
                    'title' => 'Red Corner Light Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"8","top_left":"8","bottom_left":"8","top_right":"8","bottom_right":"8","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => '#ffffff',
                    'hover_color_button' => '#f65e5e',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 11,
                    'title' => 'Red Rounded Light Button (No Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"20","top_left":"20","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 12,
                    'title' => 'Red Rounded Light Button (Hover)',
                    'edit_button' => '{"height":"35","width":"100","border":"20","top_left":"20","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"6","padding_left":"18"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => '#ffffff',
                    'hover_color_button' => '#f65e5e',
                    'hover_color_border' => '#f65e5e',
                ],
                [
                    'button_id' => 13,
                    'title' => 'Red Dashed Button',
                    'edit_button' => '{"height":"35","width":"100","border":"0","top_left":"0","bottom_left":"0","top_right":"0","bottom_right":"0","padding_top":"6","padding_left":"20"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#f65e5e',
                    'border_style' => 'dashed',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#f65e5e',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 14,
                    'title' => 'Discount Code',
                    'edit_button' => '{"height":"33","width":"136","border":"4","top_left":"4","bottom_left":"4","top_right":"4","bottom_right":"4","padding_top":"6","padding_left":"12"}',
                    'background_color' => '#444444',
                    'background_color_border' => '#ffffff',
                    'border_style' => 'dashed',
                    'border_width' => '2',
                    'size' => '14',
                    'content' => '<p><span><strong>DISCOUNTCODE</strong></span></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 15,
                    'title' => 'Fancy Button (Border Radius Top Left - Bottom Right)',
                    'edit_button' => '{"height":"34","width":"100","border":"0","top_left":"33","bottom_left":"0","top_right":"0","bottom_right":"33","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#298a68',
                    'background_color_border' => '#298a68',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 16,
                    'title' => 'Fancy Button (Border Radius Top Left - Bottom Right + Hover)',
                    'edit_button' => '{"height":"34","width":"100","border":"0","top_left":"33","bottom_left":"0","top_right":"0","bottom_right":"33","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#298a68',
                    'background_color_border' => '#298a68',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => '#298a68',
                    'hover_color_button' => '#ffffff',
                    'hover_color_border' => '#298a68',
                ],
                [
                    'button_id' => 17,
                    'title' => 'Fancy Light Button (Border Radius Top Left - Bottom Right)',
                    'edit_button' => '{"height":"34","width":"100","border":"0","top_left":"33","bottom_left":"0","top_right":"0","bottom_right":"33","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#298a68',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#298a68',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 18,
                    'title' => 'Fancy Light Button (Border Radius Top Left - Bottom Right + Hover)',
                    'edit_button' => '{"height":"34","width":"100","border":"33","top_left":"33","bottom_left":"0","top_right":"0","bottom_right":"33","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#ffffff',
                    'background_color_border' => '#298a68',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#298a68',
                    'hover_color_text' => '#ffffff',
                    'hover_color_button' => '#298a68',
                    'hover_color_border' => '#298a68',
                ],
                [
                    'button_id' => 19,
                    'title' => 'Fancy Button (Border Radius Top Right - Bottom Left - Bottom Right)',
                    'edit_button' => '{"height":"34","width":"100","border":"20","top_left":"0","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#e89721',
                    'background_color_border' => '#e89721',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => null,
                    'hover_color_button' => null,
                    'hover_color_border' => null,
                ],
                [
                    'button_id' => 20,
                    'title' => 'Fancy Button (Border Radius Top Right - Bottom Left - Bottom Right + Hover)',
                    'edit_button' => '{"height":"34","width":"100","border":"20","top_left":"0","bottom_left":"20","top_right":"20","bottom_right":"20","padding_top":"8","padding_left":"24"}',
                    'background_color' => '#e89721',
                    'background_color_border' => '#e89721',
                    'border_style' => 'solid',
                    'border_width' => '2',
                    'size' => '12',
                    'content' => '<p><strong>BUTTON</strong></p>',
                    'status' => '1',
                    'creation_time' => '',
                    'update_time' => '',
                    'text_color' => '#ffffff',
                    'hover_color_text' => '#e89721',
                    'hover_color_button' => '#ffffff',
                    'hover_color_border' => '#e89721',
                ],
            ];

            $installer->getConnection()->insertMultiple($tableName, $data);
        }
    }
}
