<?php


/** @var \Magenest\Affiliate\Block\Dashboard $block */
?>
<?php

use Magenest\Affiliate\Block\Adminhtml\Campaign\Edit\Tab\Commissions\Arraycommission;

?>

<div class="page-content">
    <?php if ($blockId = $block->getAffiliateHelper()->getDefaultPage()) : ?>
        <?= $block->loadCmsBlock($blockId) ?>
    <?php endif; ?>
</div>
<?php
$campaigns  = $block->getCampaigns();
$codeLength = $block->getAffiliateHelper()->getCodeLength();
?>
<?php if ($campaigns->getSize()) : ?>
    <div class="affiliate-campaigns-list">
        <form id="campaign-coupon-form" method="post" action="<?= $block->escapeUrl($block->getSavePrefixUrl()) ?>">
            <?php if ($campaignBlock = $block->getAffiliateHelper()->getCampaignDescriptionBlockId()) : ?>
                <?= $block->loadCmsBlock($campaignBlock) ?>
            <?php endif; ?>
            <?php if ($block->isActiveAffiliateAccount() && $block->hasCouponCode()) : ?>
                <div class="coupon" data-bind="scope: 'affiliate-coupon-prefix'">
                    <label for="campaign_coupon_prefix">
                        <h3><?= __('Coupon') ?></h3>
                        <input type="text" name="campaign_coupon_prefix" id="campaign_coupon_prefix"
                               value="<?= $block->escapeHtmlAttr(strtoupper($block->getCouponPrefix())) ?>"
                               class="input-text"
                               minlength="<?= $codeLength ?>"
                               maxlength="<?= $codeLength ?>"
                               pattern="[a-zA-Z0-9]+"
                               required/>
                    </label>
                    <button class="action primary" type="submit" title="<?= __('Save') ?>">
                        <span><?= __('Save') ?></span>
                    </button>
                </div>
            <?php endif; ?>
            <?php foreach ($campaigns as $campaign) : ?>
                <table class="data-table" id="list-campaigns-table-<?= $campaign->getId() ?>">
                    <tbody>
                    <?php
                    //fixbug unserialize $config  = null for m2 v2.1 EE
                    if ($campaign->getCommission()) {
                        $commission = $block->getAffiliateHelper()->unserialize($campaign->getCommission());
                    } else {
                        $commission = null;
                    }
                    $rowSpan   = is_array($commission) ? count($commission) : 0;
                    $extraSpan = $block->getCampaignRowSpan($rowSpan, $campaign);
                    ?>
                    <?php if (is_array($commission) && count($commission)) : ?>
                        <?php foreach ($commission as $tierId => $tierValue) : ?>
                            <tr class="mobile-device">
                                <?php if ($tierId === 'tier_1') : ?>
                                    <td class="title" rowspan="<?= $block->escapeHtmlAttr($extraSpan) ?>">
                                        <strong><?= $campaign->getName() ?></strong>
                                        <p>
                                            <?= $block->escapeHtml($campaign->getDescription()) ?>
                                        </p>
                                    </td>
                                <?php endif; ?>
                            </tr>
                            <tr class="content">
                                <?php if ($tierId === 'tier_1') : ?>
                                    <td class="title desktop-device"
                                        rowspan="<?= $block->escapeHtmlAttr($extraSpan) ?>">
                                        <strong><?= $campaign->getName() ?></strong>
                                        <p>
                                            <?= $block->escapeHtml($campaign->getDescription()) ?>
                                        </p>
                                    </td>
                                    <td rowspan="<?= $block->escapeHtmlAttr($rowSpan) ?>">
                                        <strong><?= __('Pay Per Sale') ?></strong>
                                    </td>
                                <?php endif; ?>
                                <td>
                                    <?= $tierValue['name'] ?>
                                </td>
                                <td>
                                    <?php if ($tierValue['value']) : ?>
                                        <?php if ((int)$tierValue['type'] === Arraycommission::TYPE_FIXED) : ?>
                                            <?= __('%1 for first order.', $block->formatPrice($tierValue['value'])) ?>
                                        <?php elseif ((int)$tierValue['type']
                                            === Arraycommission::TYPE_SALE_PERCENT) : ?>
                                            <?= __('%1 of Order Total for first order.', ($tierValue['value'] . '%')) ?>
                                        <?php else : ?>
                                            <?= __(
                                                '%1 of Order Profit for first order.',
                                                ($tierValue['value'] . '%')
                                            ) ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if ($tierValue['value_second']) : ?>
                                        <?php if ((int)$tierValue['type_second'] === Arraycommission::TYPE_FIXED) : ?>
                                            <?= __(
                                                '%1 for next orders.',
                                                $block->formatPrice($tierValue['value_second'])
                                            ) ?>
                                        <?php elseif ((int)$tierValue['type_second']
                                            === Arraycommission::TYPE_SALE_PERCENT) : ?>
                                            <?= __(
                                                '%1 of Order Total for next orders.',
                                                ($tierValue['value_second'] . '%')
                                            ) ?>
                                        <?php else : ?>
                                            <?= __(
                                                '%1 of Order Profit for next orders.',
                                                ($tierValue['value_second'] . '%')
                                            ) ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?= $block->getCommissionCampaignAddition('commission.campaign.addition', $campaign) ?>
                    <?php else : ?>
                    <tr class="content">
                        <?php if (!$rowSpan) : ?>
                            <td class="title" rowspan="<?= $block->escapeHtmlAttr($extraSpan + 1) ?>">
                                <strong><?= $campaign->getName() ?></strong>
                                <p>
                                    <?= $block->escapeHtml($campaign->getDescription()) ?>
                                </p>
                            </td>
                        <?php endif; ?>
                        <?= $block->getCommissionCampaignAddition('commission.campaign.addition', $campaign) ?>
                        <?php endif; ?>
                    <tr class="content">
                        <td class="box-title">
                            <strong><?= __('Discount policy') ?></strong>
                        </td>
                        <td colspan="3">
                            <?= empty($campaign->getDiscountDescription()) ? 'None'
                                : $campaign->getDiscountDescription() ?>
                        </td>
                    </tr>
                    <tr class="content">
                        <td class="box-title">
                            <strong><?= __('Valid Date') ?></strong>
                        </td>
                        <td colspan="3">
                            <?php
                            $fromDate = $campaign->getFromDate();
                            $toDate   = $campaign->getToDate();
                            ?>
                            <?php if (!$fromDate && !$toDate) : ?>
                                <?= __('Always') ?>
                            <?php else : ?>
                                <?= $fromDate ? __('from') . ' <strong>' . $block->formatDate(
                                        $fromDate,
                                        \IntlDateFormatter::MEDIUM
                                    ) . '</strong> ' : '' ?>
                                <?= $toDate ? __('to') . ' <strong>' . $block->formatDate(
                                        $toDate,
                                        \IntlDateFormatter::MEDIUM
                                    ) . '</strong>' : '' ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php if ($block->isActiveAffiliateAccount() && $campaign->getCouponCode()) : ?>
                        <tr class="content">
                            <td class="box-title">
                                <strong><?= __('Coupon code') ?></strong>
                            </td>
                            <td colspan="3">
                                <?= strtoupper($block->getCouponPrefix() . '-' . $campaign->getCouponCode()) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?= $block->getChildHtml('campaign_addition') ?>
                    </tbody>
                </table>
            <?php endforeach; ?>

        </form>
    </div>
<?php endif; ?>

<?= $block->getChildHtml('dashboard.extra') ?>
