<?php

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block affiliate-nav">
    <div class="title">
        <strong><?= /* @escapeNotVerified */ __('My Affiliate'); ?></strong>
    </div>
    <div class="content">
        <nav class="affiliate-nav">
            <ul class="nav items">
                <?= $block->renderNavigationLink(); ?>
            </ul>
        </nav>
    </div>
</div>
