<?php
/** @var \Magento\Customer\Block\Address\Edit $block */

use Magento\Customer\Helper\Address;

$cityId     = $block->getAddress()->getCustomAttribute('city_id')
    ? $block->getAddress()->getCustomAttribute('city_id')
        ->getValue() : '';
$district   = $block->getAddress()->getCustomAttribute('district')
    ? $block->getAddress()->getCustomAttribute('district')->getValue()
    : '';
$districtId = $block->getAddress()->getCustomAttribute('district_id')
    ? $block->getAddress()->getCustomAttribute('district_id')->getValue()
    : '';
$ward       = $block->getAddress()->getCustomAttribute('ward')
    ? $block->getAddress()->getCustomAttribute('ward')->getValue()
    : '';
$wardId     = $block->getAddress()->getCustomAttribute('ward_id')
    ? $block->getAddress()->getCustomAttribute('ward_id')->getValue()
    : '';
?>

<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>

<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Contact Information')) ?></span></legend>
        <br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_telephone->isEnabled()) : ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($_company->isEnabled()) : ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()) : ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Address')) ?></span></legend>
        <?php $_streetValidationClass = $this->helper(Address::class)
            ->getAttributeValidationClass('street'); ?>

        <?php if ($this->helper(Address::class)->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           placeholder="<?= $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $block->escapeHtmlAttr(
                               $this->helper(Address::class)->getAttributeValidationClass('vat_id')
                           ) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city_id">
                <span><?= $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <select id="city_id" name="city_id"
                        title="<?= $block->getAttributeData()->getFrontendLabel('city') ?>"
                        class="validate-select district_id"
                        required>
                </select>
                <input type="text"
                       name="city"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       placeholder="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr(
                           $this->helper(Address::class)->getAttributeValidationClass('city')
                       ) ?>"
                       id="city">
            </div>
        </div>
        <div class="field district required">
            <label class="label" for="district_id">
                <span><?= $block->getAttributeData()->getFrontendLabel('district') ?></span>
            </label>
            <div class="control">
                <select id="district_id" name="district_id"
                        title="<?= $block->getAttributeData()->getFrontendLabel('district') ?>"
                        class="validate-select district_id"
                        required>
                </select>
                <input type="text"
                       id="district"
                       name="district"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($district) ?>"
                       title="<?= $block->getAttributeData()->getFrontendLabel('district') ?>"
                       placeholder="<?= $block->getAttributeData()->getFrontendLabel('district') ?>"
                       class="input-text"/>
            </div>
        </div>
        <div class="field ward required">
            <label class="label" for="ward_id">
                <span><?= $block->getAttributeData()->getFrontendLabel('ward') ?></span>
            </label>
            <div class="control">
                <select id="ward_id" name="ward_id"
                        title="<?= $block->getAttributeData()->getFrontendLabel('ward') ?>"
                        class="validate-select ward_id"
                        required>
                </select>
                <input type="text"
                       id="ward"
                       name="ward"
                       style="display: none"
                       value="<?= $block->escapeHtmlAttr($ward) ?>"
                       title="<?= $block->getAttributeData()->getFrontendLabel('ward') ?>"
                       placeholder="<?= $block->getAttributeData()->getFrontendLabel('ward') ?>"
                       class="input-text"/>
            </div>
        </div>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= __('Specific Address') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $block->getAttributeData()->getFrontendLabel('street') ?>"
                       placeholder="<?= $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       class="input-text validate-specific-address"
                />
            </div>
        </div>
        <div class="field country required" style="display: none;">
            <div class="control">
                <input type="hidden" name="country_id" value="VN" title="Country" id="country" class="input-text">
            </div>
        </div>

        <?php if ($block->isDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1"
                       class="checkbox checkbox-custom" checked disabled>
                <label class="label custom-check checkbox" for="primary_billing">
                    <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
                </label>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1"
                       class="checkbox checkbox-custom">
                <label class="label custom-check checkbox" for="primary_billing">
                    <span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1"
                       class="checkbox checkbox-custom" checked disabled>
                <label class="label custom-check checkbox" for="primary_shipping">
                    <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
                </label>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1"
                       class="checkbox checkbox-custom">
                <label class="label custom-check checkbox" for="primary_shipping">
                    <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $block->escapeHtmlAttr(__('Save changes')) ?>">
                <span><?= $block->escapeHtml(__('Save changes')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Cancel changes')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        ".form-address-edit": {
            "Magenest_Directory/js/field-updater": {
                "form": "#form-validate",
                "defaultCity": "<?= (int)$cityId ?: "" ?>",
                "defaultDistrict": "<?= (int)$districtId ?: "" ?>",
                "defaultWard": "<?= (int)$wardId ?: "" ?>",
                "dataJson": <?= $this->helper(\Magenest\Directory\Helper\Data::class)->getDataJson() ?>
            }
        }
    }

</script>
<script>
    require(['jquery'], function ($) {
        $('.title-back-icon').click(function () {
            event.preventDefault();
            event.stopImmediatePropagation();
            window.location.href = "<?= $block->getUrl('customer/address/index') ?>";
        })
    })
</script>
