<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;
use Magento\Customer\Helper\Address;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
$city = $block->getCustomer()->getCustomAttribute('city_id');
$district = $block->getCustomer()->getCustomAttribute('district_id');
$ward = $block->getCustomer()->getCustomAttribute('ward_id');
/** @var \Magenest\Directory\Helper\Data $directoryHelper */
$directoryHelper = $this->helper(\Magenest\Directory\Helper\Data::class);
$cityLabel = $districtLabel = $wardLabel = false;
if ($city) {
    $cityId = $city->getValue();
    $cityData = $directoryHelper->getCityById($cityId);
    $cityLabel = $cityData ? $cityData['full_name'] : false;
    if ($district) {
        $districtId = $district->getValue();
        $districtData = $directoryHelper->getDistrictById($cityId, $districtId);
        $districtLabel = $districtData ? $districtData['full_name'] : false;
        if ($ward) {
            $wardId = $ward->getValue();
            $wardData = $directoryHelper->getWardById($cityId, $districtId, $wardId);
            $wardLabel = $wardData ? $wardData['full_name'] : false;
        }
    }
}
if ($wardLabel && $districtLabel && $cityLabel) {
    $fullAddress = implode(", ", [$wardLabel, $districtLabel, $cityLabel]);
} else {
    $fullAddress = "";
}
if ( $block->getCustomer()->getCustomAttribute('specific_address')){
    $specificAddress = $block->getCustomer()->getCustomAttribute('specific_address')->getValue();
}
else $specificAddress = "";
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend>

        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php $telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class); ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php
        $email = $block->getCustomer()->getEmail();
        $email = preg_replace('/(^[a-z\d]{2}).*?(@)/i', "$1********$2", $email);
        $telephoneValue = $block->getCustomer()->getCustomAttribute('telephone') ? $block->getCustomer()->getCustomAttribute('telephone')->getValue() : "";
        $telephoneValue = preg_replace('/.*?([\d]{2})$/i', "**********$1", $telephoneValue);
        ?>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox"/>
            <label class="label label-email">
                <?= __("Email") ?>
            </label>
            <p class="value"><?= $block->escapeHtmlAttr($email) ?></p>
            <label class="label-action" for="change-email">
                <span class="change"><?= __('Change') ?></span>
                <span class="cancel"><?= __('Cancel') ?></span>
            </label>
        </div>
        <fieldset class="fieldset password" data-container="change-email-password">
            <div class="field email required" data-container="change-email">
                <div class="control">
                    <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
        </fieldset>
        <div class="field choice">
            <input type="checkbox" name="change-telephone" id="change-telephone" data-role="change-telephone" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Phone')) ?>" class="checkbox"/>
            <label class="label label-telephone">
                <?= __("Phone Number") ?>
            </label>
            <p class="value"><?= $telephoneValue ?></p>
            <label class="label-action" for="change-telephone">
                <span class="change"><?= __('Change') ?></span>
                <span class="cancel"><?= __('Cancel') ?></span>
            </label>
        </div>
        <fieldset class="fieldset telephone" data-container="change-telephone" hidden>
            <?php if ($telephone->isEnabled()):
                $phoneNumber = $block->getCustomer()->getCustomAttribute('telephone'); ?>
                <?= $telephone->setTelephone("")->toHtml() ?>
            <?php endif ?>
        </fieldset>
        <div class="field password current required" hidden  data-input="current-password">
            <label class="label" for="current-password">
                <span><?= $block->escapeHtml(__('Current Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password"
                       autocomplete="off" />
            </div>
        </div>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <fieldset class="fieldset date-of-birth">
            <div class="field choice">
                <label class="label"><?= __('Date of birth') ?></label>
                <input type="hidden" id="dob" name="dob" value="<?= $block->getCustomer()->getDob() ? \DateTime::createFromFormat("Y-m-d", $block->getCustomer()->getDob())->format("d/m/Y") : "" ?>">
                <div class="block-flex">
                    <select id="day" name="day"></select>
                    <select id="month" name="month"></select>
                    <select id="year" name="year"></select>
                </div>
            </div>
        </fieldset>

        <fieldset class="fieldset additional_info">
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>

        <fieldset class="fieldset address-full">
            <div class="field">
                <label class="label"><?= __('Province/city, district/district, ward/commune') ?></label>
                <input class="input-text full-directory-information" type="text" readonly value="<?= $fullAddress ?>" placeholder="<?= __("Please select city, district and ward") ?>" data-value-bind="value: fullDirectoryInformation, click: clickOpenDirectory">
            </div>
            <div class="fieldset field address-full-details-wrapper" style="display: none;">
                <div class="field _required" name="shippingAddress.city_id">
                    <label class="label" for="city_id">
                        <span><?= __('City') ?></span>
                    </label>
                    <div class="control">
                        <select id="city_id" name="city_id"
                                title="<?= __('City') ?>"
                                class="validate-select city_id"
                                required>
                            <option value=""><?= __("Please select city") ?></option>
                        </select>
                        <input type="text"
                               name="city"
                               style="display: none"
                               value="<?= $block->escapeHtmlAttr($city ? $city->getValue() : "") ?>"
                               title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('City')) ?>"
                               class="input-text <?= $block->escapeHtmlAttr(
                                   $this->helper(Address::class)->getAttributeValidationClass('city')
                               ) ?>"
                               id="city">
                    </div>
                </div>
                <div class="field _required" name="shippingAddress.district_id">
                    <label class="label" for="district_id">
                        <span><?= __('District') ?></span>
                    </label>
                    <div class="control" >
                        <select id="district_id" name="district_id"
                                title="<?= __('District') ?>"
                                class="validate-select district_id"
                                required>
                            <option value=""><?= __("Please select district") ?></option>
                        </select>
                        <input type="text"
                               id="district"
                               name="district"
                               style="display: none"
                               value="<?= $district ? $district->getValue() : "" ?>"
                               title="<?= __('District') ?>"
                               placeholder="<?= __('District') ?>"
                               class="input-text"/>
                    </div>
                </div>
                <div class="field _required" name="shippingAddress.ward_id">
                    <label class="label" for="ward_id">
                        <span><?= __("Ward") ?></span>
                    </label>
                    <div class="control">
                        <select id="ward_id" name="ward_id"
                                title="<?= __('Ward') ?>"
                                class="validate-select ward_id"
                                required>
                            <option value=""><?= __("Please select ward") ?></option>
                        </select>
                        <input type="text"
                               id="ward"
                               name="ward"
                               style="display: none"
                               value="<?= $ward ? $ward->getValue() : "" ?>"
                               title="<?= __('Ward') ?>"
                               placeholder="<?= __('Ward') ?>"
                               class="input-text"/>
                    </div>
                </div>
            </div>
            <div class="field-error" id="directory-error" hidden>
                <span><?= __('Please check and select city, district and ward') ?></span>
            </div>
        </fieldset>

        <fieldset class="fieldset specific-address">
            <div class="field specific_address">
                <label class="label" for="specific_address"><?= __('Specific Address') ?></label>
                <input type="text" name="specific_address" id="specific_address" placeholder="<?= __('Specific Address') ?>"
                       class="input-text"
                       value="<?= $specificAddress ?>">
            </div>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                    <span><?= $block->escapeHtml(__('Save changes')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Cancel changes')) ?></span>
                </a>
            </div>
        </div>

    </fieldset>
    <fieldset class="fieldset field-name-avatar">
        <?php $avatarFile = !empty($block->getCustomer()->getCustomAttribute('profile_picture')) ? $block->getLayout()->createBlock('\Magenest\CustomerAvatar\Block\Attributes\Avatar')->checkImageFile(base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())) : false; ?>
        <?php $avatar = ($avatarFile) ? $block->getUrl('viewfile/avatar/view/', ['image' => base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())]) : $block->getViewFileUrl('Magenest_CustomerAvatar::images/user-default.svg'); ?>
        <img id="avatar_customer" src="<?= $escaper->escapeUrl($avatar); ?>" width="150px" height="150px"
             alt="profile-picture" title="<?= __('Upload new avatar'); ?>" class="profile-image"/>
        <div class="control">
            <label for="profile_picture" class="avatar-file-upload">
                <?php echo __('Edit'); ?>
            </label>
            <input hidden type="file" id="profile_picture" name="profile_picture" value="" title="Your avatar"
                   class="avatar validate-image"/>
        </div>
        <p class="avatar-customer-desc desktop-device">
            <span><?= __('Maximum file size 1 MB') ?></span>
            <span><?= __('Format: .JPEG, .PNG') ?></span>
        </p>
    </fieldset>
</form>
<?php $ignore = /* @noEscape */
    $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = {$ignore};

        dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
        });
    });
script;
?>
<?= /* @noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $changeEmailAndPasswordTitle = $block->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password], [data-role=change-telephone]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangeTelephone": "<?= $block->escapeJs($block->escapeHtml(__('Change Telephone'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }


</script>
<script>
    require(['jquery'], function ($) {
        let btnShowPassword = $('.show-password');
        let inputChangeImage = $('#profile_picture');
        let previewImage = $('#avatar_customer');

        btnShowPassword.on('click', function () {
            let input = $(this).siblings('.input-text');
            let inputType = input.attr('type');

            if (inputType === 'password') {
                $(this).addClass('show');
                input.attr('type', 'text');
            } else {
                $(this).removeClass('show');
                input.attr('type', 'password');
            }
        })

        inputChangeImage.change(function () {
            const [file] = this.files
            if (file) {
                previewImage.attr('src', URL.createObjectURL(file));
            }
        });
        var customerDob = new Date('<?= $block->getCustomer()->getDob() ?>');
        var selectedDay = customerDob.getDate();
        var selectedMon = customerDob.getMonth()+1;
        var selectedYear = customerDob.getFullYear();

        var Days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
        var selectDay = $('#day'),
            selectMonth = $('#month'),
            selectYear = $('#year');

        var optionDay = '<option value="day"><?= __('Day') ?></option>';

        for (let i = 1; i <= Days[0]; i++) {
            optionDay += `<option value="${i}">${i}</option>`;
        }
        selectDay.append(optionDay);
        selectDay.val(isNaN(parseFloat(selectedDay)) ? "day" : selectedDay );

        var optionMonth = '<option value="month"><?= __('Month') ?></option>';

        for (let i = 1; i <= 12; i++) {
            optionMonth += `<option value="${i}"><?= __('Month') ?> ${i}</option>`;
        }

        selectMonth.append(optionMonth);
        selectMonth.val(isNaN(parseFloat(selectedMon)) ? "month" : selectedMon);

        var d = new Date();
        var optionYear = '<option value="year"><?= __('Year') ?></option>';

        for (let i = 1930; i <= d.getFullYear(); i++) {
            optionYear += `<option value="${i}">${i}</option>`;
        }

        selectYear.append(optionYear);
        selectYear.val(isNaN(parseFloat(selectedYear)) ? "year" : selectedYear);

        function isLeapYear(year) {
            year = parseInt(year);
            if (year % 4 !== 0) {
                return false;
            } else if (year % 400 === 0) {
                return true;
            } else return year % 100 !== 0;
        }

        selectYear.on('change', function () {
            if (isLeapYear($(this).val())) {
                Days[1] = 29;

            } else {
                Days[1] = 28;
            }

            if (selectMonth.val() === 2) {
                var day = selectDay;
                var val = $(day).val();
                $(day).empty();
                var option = '<option value="day"><?= __('Day') ?></option>';
                for (let i = 1; i <= Days[1]; i++) { //add option days
                    option += `<option value="${i}">${i}</option>`;
                }
                $(day).append(option);
                if (val > Days[month]) {
                    val = 1;
                }
                $(day).val(val);
            }
        });

        selectMonth.on('change', function () {
            var day = selectDay;
            var val = $(day).val();
            var option = '<option value="day"><?= __('Day') ?></option>';
            var month = parseInt($(this).val()) - 1;

            $(day).empty();

            for (let i = 1; i <= Days[month]; i++) { //add option days
                option += `<option value="${i}">${i}</option>`;
            }

            $(day).append(option);

            if (val > Days[month]) {
                val = 1;
            }

            $(day).val(val);
        });

        $('.date-of-birth select').on('change', function () {
            selectDay = $('#day').val();
            selectedMon = $('#month').val();
            selectedYear = $('#year').val();

            if (selectedYear !== "year" && selectedMon !== "month" && selectDay !== "day") {
                if (selectedMon < 10) {
                    selectedMon = "0" + selectedMon;
                }
                if (selectDay < 10) {
                    selectDay = "0" + selectDay;
                }
                $('#dob').val([selectDay, selectedMon, selectedYear].join("/"));
            }
        });
    });
</script>
<script type="text/x-magento-init">
    {
        ".form-edit-account": {
            "Magenest_Directory/js/full-directory-field-updater": {
                "form": "#form-validate",
                "defaultCity": "<?= $cityId ?? "" ?>",
                "defaultDistrict": "<?= $districtId ?? "" ?>",
                "defaultWard": "<?= $wardId ?? "" ?>",
                "fullAddress": "<?= $fullAddress ?>",
                "htmlIdPrefix" : "",
                "dataJson": <?=  $directoryHelper->getDataJson() ?>
            }
        }
    }
</script>
