<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend>

        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php $telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class); ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <!--@Todo: Format email, telephone -> da********@gmail.com, **********77-->
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label label-email">
                <?= __("Email") ?>
            </label>
            <p class="value"><?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?></p>
            <label class="label-action" for="change-email">
                <span class="change"><?= __('Change') ?></span>
                <span class="cancel"><?= __('Cancel') ?></span>
            </label>
        </div>
        <fieldset class="fieldset password" data-container="change-email-password">
            <div class="field email required" data-container="change-email">
                <div class="control">
                    <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                           value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <!--<div class="field password current required">
                <label class="label" for="current-password">
                    <span><?/*= $block->escapeHtml(__('Current Password')) */?></span>
                </label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password"
                           data-input="current-password"
                           autocomplete="off" />
                    <span class="show-password"></span>
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?/*= $block->escapeHtml(__('Social account will have default password equal to email. Please changes it after first logging in!')) */?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field new password required" data-container="new-password">
                <label class="label" for="password"><span><?/*= $block->escapeHtml(__('New Password')) */?></span></label>
                <div class="control">
                    <?php /*$minCharacterSets = $block->getRequiredCharacterClassesNumber() */?>
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?/*= $block->escapeHtml($block->getMinimumPasswordLength()) */?>"
                           data-password-min-character-sets="<?/*= $block->escapeHtml($minCharacterSets) */?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <span class="show-password"></span>
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?/*= $block->escapeHtml(__('Password Strength')) */?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?/*= $block->escapeHtml(__('No Password')) */?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirmation password required" data-container="confirm-password">
                <label class="label" for="password-confirmation">
                    <span><?/*= $block->escapeHtml(__('Enter the password')) */?></span>
                </label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off" />
                    <span class="show-password"></span>
                </div>
            </div>-->
        </fieldset>
        <!--@Todo: Get telephone-->
        <div class="field choice">
            <input type="checkbox" name="change-telephone" id="change-telephone" data-role="change-telephone" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Phone')) ?>" class="checkbox" />
            <label class="label label-telephone">
                <?= __("Phone Number") ?>
            </label>
            <p class="value">091323232323</p>
            <label class="label-action" for="change-telephone">
                <span class="change"><?= __('Change') ?></span>
                <span class="cancel"><?= __('Cancel') ?></span>
            </label>
        </div>
        <fieldset class="fieldset telephone" data-container="change-telephone">
            <?php if ($telephone->isEnabled()):
                $phoneNumber = $block->getCustomer()->getCustomAttribute('telephone'); ?>
                <?= $telephone->setTelephone($phoneNumber ? $phoneNumber->getValue() : "")->toHtml() ?>
            <?php endif ?>
        </fieldset>
        <!--<div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                   title="<?/*= $block->escapeHtmlAttr(__('Change Password')) */?>"
                <?php /*if ($block->getChangePassword()): */?> checked="checked"<?php /*endif; */?> class="checkbox" />
            <label class="label custom-check checkbox" for="change-password">
                <span><?/*= $block->escapeHtml(__('Change Password')) */?></span>
            </label>
        </div>-->
        <!--  <?//= $block->getChildHtml('fieldset_edit_info_additional') ?>  -->

        <fieldset class="fieldset sex">
            <div class="field choice">
                <label class="label">
                    <?= __('Sex') ?>
                </label>
                <div class="control">
                    <label>
                        <input type="radio" name="sex" id="male" />
                        <span class="label custom-check radio">
                        <?= __('Male') ?>
                    </span>
                    </label>
                    <label>
                        <input type="radio" name="sex" id="female" />
                        <span  class="label custom-check radio">
                        <?= __('Female') ?>
                    </span>
                    </label>
                    <label >
                        <input type="radio" name="sex" id="other" />
                        <span class="label custom-check radio">
                        <?= __('Other') ?>
                    </span>
                    </label>
                </div>
            </div>
        </fieldset>

        <fieldset class="fieldset date-of-birth">
            <select id ="year" name = "yyyy" onchange="change_year(this)"></select>
            <select id ="month" name = "mm" onchange="change_month(this)"></select>
            <select id ="day" name = "dd" ></select>
        </fieldset>

        <fieldset class="fieldset additional_info">
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                    <span><?= $block->escapeHtml(__('Save changes')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Cancel changes')) ?></span>
                </a>
            </div>
        </div>

    </fieldset>
    <fieldset class="fieldset field-name-avatar">
        <?php $avatarFile = !empty($block->getCustomer()->getCustomAttribute('profile_picture')) ? $block->getLayout()->createBlock('\Magenest\CustomerAvatar\Block\Attributes\Avatar')->checkImageFile(base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())) : false; ?>
        <?php $avatar = ($avatarFile) ? $block->getUrl('viewfile/avatar/view/', ['image' => base64_encode($block->getCustomer()->getCustomAttribute('profile_picture')->getValue())]) : $block->getViewFileUrl('Magenest_CustomerAvatar::images/user-default.svg');?>
        <label class="label" for="profile_picture">
            <img id="avatar_customer" src="<?= $escaper->escapeUrl($avatar); ?>" width="150px" height="150px" alt="profile-picture" title="<?= __('Upload new avatar'); ?>" class="profile-image"/>
        </label>
        <div class="control">
            <label for="profile_picture" class="avatar-file-upload">
                <?php echo __('Edit'); ?>
            </label>
            <input hidden type="file" id="profile_picture" name="profile_picture" value="" title="Your avatar" class="avatar validate-image" />
        </div>
    </fieldset>
</form>
<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = {$ignore};

        dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
        });

    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $changeEmailAndPasswordTitle = $block->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password], [data-role=change-telephone]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangeTelephone": "<?= $block->escapeJs($block->escapeHtml(__('Change Telephone'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<script>
    require(['jquery'], function($){
        let btnShowPassword = $('.show-password');
        let inputChangeImage = $('#profile_picture');
        let previewImage = $('#avatar_customer');

        btnShowPassword.on('click', function () {
            let input = $(this).siblings('.input-text');
            let inputType = input.attr('type');

            if (inputType === 'password') {
                $(this).addClass('show');
                input.attr('type', 'text');
            } else  {
                $(this).removeClass('show');
                input.attr('type', 'password');
            }
        })

        inputChangeImage.change(function() {
            const [file] = this.files
            if (file) {
                previewImage.attr('src', URL.createObjectURL(file));
            }
        });

        var Days = [31,28,31,30,31,30,31,31,30,31,30,31];// index => month [0-11]
        var optionDay = '<option value="day">day</option>';
        var selectedDay="day";
        for (var i=1;i <= Days[0];i++){ //add option days
            option += '<option value="'+ i + '">' + i + '</option>';
        }
        $('#day').append(optionDay);
        $('#day').val(selectedDay);

        var optionMonth = '<option value="month">month</option>';
        var selectedMon ="month";
        for (var i=1;i <= 12;i++){
            option += '<option value="'+ i + '">' + i + '</option>';
        }
        $('#month').append(optionMonth);
        $('#month').val(selectedMon);

        var option = '<option value="month">month</option>';
        var selectedMon ="month";
        for (var i=1;i <= 12;i++){
            option += '<option value="'+ i + '">' + i + '</option>';
        }
        $('#month2').append(option);
        $('#month2').val(selectedMon);

        var d = new Date();
        var option = '<option value="year">year</option>';
        selectedYear ="year";
        for (var i=1930;i <= d.getFullYear();i++){// years start i
            option += '<option value="'+ i + '">' + i + '</option>';
        }
        $('#year').append(option);
        $('#year').val(selectedYear);
        function isLeapYear(year) {
            year = parseInt(year);
            if (year % 4 != 0) {
                return false;
            } else if (year % 400 == 0) {
                return true;
            } else if (year % 100 == 0) {
                return false;
            } else {
                return true;
            }
        }

        function change_year(select)
        {
            if( isLeapYear( $(select).val() ) )
            {
                Days[1] = 29;

            }
            else {
                Days[1] = 28;
            }
            if( $("#month").val() == 2)
            {
                var day = $('#day');
                var val = $(day).val();
                $(day).empty();
                var option = '<option value="day">day</option>';
                for (var i=1;i <= Days[1];i++){ //add option days
                    option += '<option value="'+ i + '">' + i + '</option>';
                }
                $(day).append(option);
                if( val > Days[ month ] )
                {
                    val = 1;
                }
                $(day).val(val);
            }
        }

        function change_month(select) {
            var day = $('#day');
            var val = $(day).val();
            $(day).empty();
            var option = '<option value="day">day</option>';
            var month = parseInt( $(select).val() ) - 1;
            for (var i=1;i <= Days[ month ];i++){ //add option days
                option += '<option value="'+ i + '">' + i + '</option>';
            }
            $(day).append(option);
            if( val > Days[ month ] )
            {
                val = 1;
            }
            $(day).val(val);
        }
    });
</script>
