<?php
namespace Magenest\PhotoReview\Model\Mail;

class TransportBuilder extends \Magento\Framework\Mail\Template\TransportBuilder
{
    protected $body;
    protected $subject;
    protected $from;
    protected $version;

    /**
     * @return \Magento\Framework\Mail\MessageInterface
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @return TransportBuilder|\Magento\Framework\Mail\Template\TransportBuilder
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function prepare()
    {
        return $this->prepareMessage();
    }

    /**
     * @return $this
     */
    public function clearFrom()
    {
        $this->message->clearFrom('From');
        return $this;
    }

    /**
     * @return $this
     */
    public function clearSubject()
    {
        $this->message->clearSubject();
        return $this;
    }

    /**
     * @return $this
     */
    public function clearMessageId()
    {
        $this->message->clearMessageId();
        return $this;
    }

    /**
     * @return $this
     */
    public function clearBody()
    {
        $this->message->setParts([]);
        return $this;
    }

    /**
     * @return $this
     */
    public function clearRecipients()
    {
        $this->message->clearRecipients();
        return $this;
    }

    /**
     * @param $headerName
     *
     * @return $this
     */
    public function clearHeader($headerName)
    {
        if (isset($this->_headers[$headerName])){
            unset($this->_headers[$headerName]);
        }
        return $this;
    }

    /**
     * @param $body
     * @param $subject
     * @param $from
     * @param $version
     */
    public function setMessageContent($body, $subject, $from, $version)
    {
        $this->body    = $body;
        $this->subject = $subject;
        $this->from    = $from;
        $this->version = $version;
    }

    /**
     * @return $this|\Magento\Framework\Mail\Template\TransportBuilder
     * @throws \Magento\Framework\Exception\MailException
     */
    protected function prepareMessage()
    {
        if ($this->from && version_compare($this->version, '2.3.0') < 0) {
            $from = $this->_senderResolver->resolve(
                $this->from
            );
            $this->message->setMessageType('text/html')->setBody($this->body)->setSubject($this->subject, ENT_QUOTES)->setFromAddress($from['email'], $from['name']);
        }else{
            $this->message->setMessageType('text/html')->setBody($this->body)->setSubject($this->subject, ENT_QUOTES);
        }
        return $this;
    }

    /**
     * @return \Magento\Framework\Mail\Template\TransportBuilder
     */
    public function reset()
    {
        return parent::reset(); // TODO: Change the autogenerated stub
    }
}
